/* ============================================================
   Félag · app shell.

   Data comes from data/questions.jsonl, generated by
   tools/content.py from SIRI's published papers and answer keys.
   Explanations are joined by id from data/explanations.jsonl so
   regenerating the bank can never destroy hand-written work.
   ============================================================ */

import { CAST, byId } from './cast.js';
import * as scenes from './scenes.js';

const $ = (id) => document.getElementById(id);
const SAVE = 'felag.v1';

/* ---------- exam rules, straight from SIRI ----------
   45 questions: 35 from the læremateriale, 5 current affairs,
   5 on Danish values. Pass needs 36 correct AND at least 4 of
   the 5 values questions. The values gate fails people who
   otherwise scored well, so it is modelled explicitly. */
const RULES = { total: 45, pass: 36, values: 5, valuesPass: 4, minutes: 45 };

const state = {
  guide: null,
  bank: [],
  best: {},
  sound: false,
  run: null,
};

/* ============================================================
   Persistence
   ============================================================ */
function load() {
  try {
    Object.assign(state, JSON.parse(localStorage.getItem(SAVE) ?? '{}'));
  } catch { /* corrupt or blocked storage is not worth a crash */ }
}
function save() {
  try {
    localStorage.setItem(SAVE, JSON.stringify({
      guide: state.guide, best: state.best, sound: state.sound, cleared: state.cleared,
    }));
  } catch { /* private mode: run without persistence rather than fail */ }
}

/* ============================================================
   Deterministic shuffling

   Option order is randomised so nobody learns "the answer is C".
   That matters here: across the 13 published papers C is correct
   39.3% of the time on three-option questions where chance says
   33.3%, so fixed order teaches a position habit instead of the
   content. The shuffle is seeded so a given run is reproducible,
   which is what later makes shared ghost battles fair.
   ============================================================ */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const hash = (s) => [...s].reduce((h, c) => Math.imul(h ^ c.charCodeAt(0), 16777619), 2166136261);

function shuffle(list, rand) {
  const out = [...list];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function present(entry, seed) {
  // ponytail: Ja/Nej keeps its natural order. With two options, knowing "Ja"
  // already is knowing the content, so shuffling only makes the UI feel wrong.
  const yesNo = entry.options.length === 2 && entry.options.every((o) => /^(Ja|Nej)$/.test(o));
  const options = yesNo ? entry.options : shuffle(entry.options, rng(hash(entry.id + seed)));
  return { ...entry, options, answerAt: options.indexOf(entry.answer) };
}

/* ============================================================
   Sound: synthesised, no audio files ship with this
   ============================================================ */
let audio = null;
function tone(freq, dur = 0.12, type = 'sine', gain = 0.05) {
  if (!state.sound) return;
  audio ??= new (window.AudioContext ?? window.webkitAudioContext)();
  const osc = audio.createOscillator();
  const amp = audio.createGain();
  osc.type = type;
  osc.frequency.value = freq;
  amp.gain.setValueAtTime(gain, audio.currentTime);
  amp.gain.exponentialRampToValueAtTime(0.0001, audio.currentTime + dur);
  osc.connect(amp).connect(audio.destination);
  osc.start();
  osc.stop(audio.currentTime + dur);
}
const sfx = {
  hit: () => { tone(660, 0.1); setTimeout(() => tone(990, 0.16), 70); },
  miss: () => tone(150, 0.22, 'triangle', 0.04),
  done: () => [523, 659, 784].forEach((f, i) => setTimeout(() => tone(f, 0.3), i * 110)),
};

/* ============================================================
   The six halls

   The six chapters of the læremateriale, in order, supplying the
   35 questions of the paper that are drawn from it. You practise
   as you study: clear a hall and the next opens. Nothing is
   locked forever, and the tests below stay open from the start,
   so the gate paces the study without ever barring the door.
   ============================================================ */
const HALL_PASS = 0.8;   // the real paper needs 36 of 45, the same ratio

const HALLS = [
  { numeral: 'I', chapter: 1, accent: '--thor', da: 'Danmarks historie', en: "Denmark's history",
    topics: ['Vikingetid', 'Middelalder', 'Enevælden', 'De slesvigske krige', 'Verdenskrigene', 'Velfærd og oprør'] },
  { numeral: 'II', chapter: 2, accent: '--gorm', da: 'Det danske demokrati', en: 'Danish democracy',
    topics: ['Styreformen', 'Grundloven', 'Folketinget', 'Retssamfundet'] },
  { numeral: 'III', chapter: 3, accent: '--ingrid', da: 'Den danske økonomi', en: 'The Danish economy',
    topics: ['Velfærdssamfundet', 'Erhvervslivet', 'Arbejdsmarkedet'] },
  { numeral: 'IV', chapter: 4, accent: '--freja', da: 'Danmark og omverdenen', en: 'Denmark and the world',
    topics: ['Danmark i Europa', 'Globalt samarbejde', 'Forsvar og sikkerhed'] },
  { numeral: 'V', chapter: 5, accent: '--astrid', da: 'Dansk kulturliv', en: 'Danish cultural life',
    topics: ['Litteratur', 'Billedkunst', 'Musik', 'Arkitektur', 'Scenekunst', 'Film'] },
  { numeral: 'VI', chapter: 6, accent: '--bjorn', da: 'Temaopslag', en: 'Thematic entries',
    topics: ['Flaget', 'Kongehuset', 'Rigsfællesskabet', 'Grundtvig', 'Ligestilling', 'Klima'] },
];

const inChapter = (n) =>
  state.bank.filter((q) => q.section === 'laeremateriale' && q.chapter === n);

function hallMode(hall, index) {
  const stock = inChapter(hall.chapter);
  return {
    id: `hal-${hall.chapter}`,
    da: `Hal ${hall.numeral}. ${hall.da}`,
    accent: hall.accent,
    hall, index,
    build: () => weighted(stock, Math.min(12, stock.length)),
  };
}

function renderHalls() {
  const cleared = state.cleared ?? 0;
  $('halls').innerHTML = HALLS.map((hall, i) => {
    const shut = i > cleared;
    const done = i < cleared;
    const stock = inChapter(hall.chapter).length;
    const state_ = done ? 'Ryddet' : shut ? 'Låst' : 'Åben';
    return `<div class="hall ${done ? 'done' : ''} ${shut ? 'shut' : ''}"
        style="--accent:var(${hall.accent}); --d:${i * 0.06}s">
        <span class="thread"></span>
        <span class="node">${done ? '&#10003;' : hall.numeral}</span>
        <button class="body" type="button" data-i="${i}" ${shut ? 'disabled' : ''}>
          <span class="names">
            <span class="da">${hall.da}</span>
            <span class="en">${hall.en}</span>
            <span class="state">${state_}</span>
          </span>
          <span class="chips">${hall.topics.map((t) => `<span>${t}</span>`).join('')}
            <span>${stock} spørgsmål</span></span>
        </button>
      </div>`;
  }).join('');
}

/* ============================================================
   Modes
   ============================================================ */
const MODES = [
  {
    id: 'ovelse', da: 'Øvelse', en: 'Practice', accent: '--freja',
    blurb: 'Tilfældige spørgsmål fra lærematerialet, vægtet efter hvor ofte SIRI faktisk har stillet dem.',
    tag: 'Ubegrænset',
    build: () => weighted(pool('laeremateriale'), 15),
  },
  {
    id: 'ting', da: 'Tinget', en: 'The values assembly', accent: '--ingrid',
    blurb: 'De 5 værdispørgsmål. Du skal have mindst 4 rigtige, ellers dumper du hele prøven uanset resten.',
    tag: 'Kræver 4 af 5',
    build: () => pick(pool('vaerdier'), RULES.values),
    gate: { need: RULES.valuesPass, of: RULES.values },
  },
  {
    id: 'alting', da: 'Altinget', en: 'The full assembly', accent: '--thor',
    blurb: 'Hele prøven under rigtige regler: 45 spørgsmål, 36 for at bestå, og mindst 4 af 5 værdispørgsmål.',
    tag: '45 spørgsmål',
    build: () => [
      ...pick(pool('laeremateriale'), 35),
      ...pick(pool('aktuelt'), 5),
      ...pick(pool('vaerdier'), 5),
    ],
    exam: true,
  },
];

/** Each mode keeps its own place, including on the result screen. */
const sceneFor = (mode) => (mode.id === 'ting' ? 'ting' : mode.exam ? 'alting' : 'hall');

const pool = (section) => state.bank.filter((q) => q.section === section);
const pick = (list, n) => shuffle(list, Math.random).slice(0, Math.min(n, list.length));

/** Frequency-weighted draw: questions SIRI asks often come up more. */
function weighted(list, n) {
  const bag = list.flatMap((q) => Array(Math.min(q.seen.length, 4)).fill(q));
  const out = [];
  const taken = new Set();
  while (out.length < Math.min(n, list.length) && bag.length) {
    const q = bag[Math.floor(Math.random() * bag.length)];
    if (!taken.has(q.id)) { taken.add(q.id); out.push(q); }
  }
  return out;
}

/* ============================================================
   Views
   ============================================================ */
const VIEWS = ['viewShore', 'viewPath', 'viewQuiz', 'viewResult'];
function go(id, scene) {
  const swap = () => {
    VIEWS.forEach((v) => { $(v).hidden = v !== id; });
    if (scene) scenes.show(scene);
    $('hud').hidden = id === 'viewShore';
    scrollTo({ top: 0, behavior: 'instant' });
  };
  // Native view transitions; browsers without it simply get the swap.
  document.startViewTransition ? document.startViewTransition(swap) : swap();
}

/* ---------- shore ---------- */
function renderShore() {
  $('roster').innerHTML = CAST.map((c, i) => `
    <button class="char" type="button" data-id="${c.id}" aria-pressed="false"
      style="--accent:var(${c.accent}); --d:${i * 0.07}s">
      <figure>${c.svg}</figure>
      <b>${c.name}</b><span>${c.style}</span>
    </button>`).join('');

  const roster = $('roster');
  roster.addEventListener('click', (e) => {
    const btn = e.target.closest('.char');
    if (btn) choose(btn.dataset.id);
  });
  // Double-click picks and walks on in one go. The button stays the primary
  // path: touch has no dblclick, so this is a shortcut, never the only way.
  roster.addEventListener('dblclick', (e) => {
    const btn = e.target.closest('.char');
    if (!btn) return;
    choose(btn.dataset.id);
    begin();
  });
  // Keyboard parity: Enter on a focused guide does the same as double-click.
  roster.addEventListener('keydown', (e) => {
    const btn = e.target.closest('.char');
    if (!btn || e.key !== 'Enter') return;
    e.preventDefault();
    choose(btn.dataset.id);
    begin();
  });
}

function choose(id) {
  const c = byId(id);
  state.guide = id;
  save();
  document.querySelectorAll('.char').forEach((el) =>
    el.setAttribute('aria-pressed', String(el.dataset.id === id)));
  const banner = $('banner');
  banner.style.setProperty('--accent', `var(${c.accent})`);
  banner.innerHTML = `
    <span class="banner-name" style="color:var(${c.accent})">${c.name} &middot; ${c.style}</span>
    <span class="banner-line">&ldquo;${c.quote}&rdquo;</span>
    <span class="banner-strength">${c.strength}</span>`;
  $('beginBtn').disabled = false;
  tone(520, 0.09);
}

/* ---------- path ---------- */
function renderPath() {
  const c = byId(state.guide) ?? CAST[0];
  $('walker').innerHTML = c.svg;
  $('guideName').textContent = c.name;
  $('pathSub').textContent = c.recommends;

  renderHalls();
  $('modes').innerHTML = MODES.map((m, i) => {
    const best = state.best[m.id];
    return `<button class="mode" type="button" data-id="${m.id}"
        style="--accent:var(${m.accent}); --d:${i * 0.08}s">
        <h3>${m.da} ${best ? `<span class="best">bedste ${best}</span>` : ''}</h3>
        <span class="en">${m.en}</span>
        <p>${m.blurb}</p>
        <span class="tag">${m.tag}</span>
      </button>`;
  }).join('');
}

/* ---------- quiz ---------- */
const SHIP = `<svg viewBox="0 0 24 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 13.2C5 15.6 8.6 16.6 12 16.6c3.4 0 7-1 9-3.4-3 1.2-6.6 1.5-9 1.5-2.4 0-6-.3-9-1.5Z" fill="currentColor"/>
  <path d="M3.4 13C1.9 12.1 1.3 9.9 2.2 7.9c.6 1.5 1.5 2.7 2.7 3.6-.5.6-1 1.1-1.5 1.5Z" fill="currentColor"/>
  <path d="M20.6 13c1.9-1.7 2.6-4.7 1.4-7.3-.6 1.8-1.7 3.4-3.4 4.5.7 1 1.4 2 2 2.8Z" fill="currentColor"/>
  <rect x="11.5" y="3.2" width="1" height="10.4" fill="currentColor"/>
  <path d="M8.2 4.6c0-.6.5-1 1.1-1h5.4c.6 0 1.1.4 1.1 1l-.7 4.5c-1.6.9-4.6.9-6.2 0Z" fill="currentColor"/></svg>`;

function start(modeId, override) {
  const mode = override ?? MODES.find((m) => m.id === modeId);
  const seed = Date.now();
  const questions = mode.build().map((q) => present(q, seed));
  if (!questions.length) return;

  state.run = {
    mode, seed, questions, i: 0, marks: Array(questions.length).fill(null),
    deadline: mode.exam ? Date.now() + RULES.minutes * 60000 : null,
  };
  $('hudTitle').textContent = mode.da;
  $('hudBackLabel').textContent = 'Forlad';
  go('viewQuiz', sceneFor(mode));
  renderQuestion();
  if (state.run.deadline) tick();
}

function tick() {
  const run = state.run;
  if (!run?.deadline) return;
  const left = run.deadline - Date.now();
  if (left <= 0) return finish();
  $('hudMeta').textContent =
    `${String(Math.floor(left / 60000)).padStart(2, '0')}:${String(Math.floor(left / 1000) % 60).padStart(2, '0')}`;
  setTimeout(tick, 1000);
}

function renderFleet() {
  const { marks, i } = state.run;
  $('fleet').innerHTML = marks.map((m, n) =>
    `<i class="${m === true ? 'hit' : m === false ? 'miss' : n === i ? 'now' : ''}">${SHIP}</i>`).join('');
}

function renderQuestion() {
  const run = state.run;
  const q = run.questions[run.i];
  const letters = ['A', 'B', 'C'];

  if (!run.deadline) $('hudMeta').textContent = `${run.i + 1} / ${run.questions.length}`;
  renderFleet();
  $('quizNext').disabled = true;
  $('quizNextLabel').textContent =
    run.i === run.questions.length - 1 ? 'Afslut' : 'Næste';

  $('quizCard').innerHTML = `
    <p class="q">${q.q}</p>
    ${q.options.map((o, n) => `
      <button class="opt" type="button" data-n="${n}" style="--d:${n * 0.05}s">
        <em>${letters[n]}</em><span>${o}</span>
      </button>`).join('')}`;

  $('quizCard').querySelectorAll('.opt').forEach((btn) =>
    btn.addEventListener('click', () => answer(Number(btn.dataset.n)), { once: true }));
}

function answer(chosen) {
  const run = state.run;
  const q = run.questions[run.i];
  const right = chosen === q.answerAt;
  run.marks[run.i] = right;

  const opts = [...$('quizCard').querySelectorAll('.opt')];
  opts.forEach((b) => { b.disabled = true; });
  opts[q.answerAt].classList.add('hit');
  if (!right) opts[chosen].classList.add('miss');
  right ? sfx.hit() : sfx.miss();
  renderFleet();

  $('quizCard').append(buildWhy(q, right));
  $('quizNext').disabled = false;
}

/* ---------- the panel after an answer ----------
   Three relics rotate so the panel never looks like the same box twice. */
const RELICS = [
  { label: 'Runefund', svg: `<svg viewBox="0 0 24 24" fill="none"><rect x="10.2" y="9" width="3.6" height="12" rx="1" fill="currentColor"/><path d="M5 4h14a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1Z" fill="currentColor"/></svg>` },
  { label: 'Fra sagaerne', svg: `<svg viewBox="0 0 24 24" fill="none"><path d="M3 15c2.5 2 5.8 3 9 3s6.5-1 9-3l-1.7 4.2a2 2 0 0 1-1.86 1.3H6.56a2 2 0 0 1-1.86-1.3L3 15Z" fill="currentColor"/><path d="M12 2v9M12 4c2.2 0 4 1.3 4 3-2 0-4-.5-4-3Z" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/><path d="M6 12V9.5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/></svg>` },
  { label: 'Skjoldmærke', svg: `<svg viewBox="0 0 24 24" fill="none"><path d="M12 2 5 5v6c0 5 3 8.5 7 11 4-2.5 7-6 7-11V5l-7-3Z" fill="currentColor" opacity=".9"/><path d="M12 2v20M5 11h14" stroke="#1c2e2f" stroke-width="1.1"/></svg>` },
];

const WARN = `<svg viewBox="0 0 24 24" fill="none"><path d="M12 3.5 22 20H2L12 3.5Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M12 10v4M12 17h.01" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>`;

const CHAPTERS = {
  1: 'Danmarks historie', 2: 'Det danske demokrati', 3: 'Den danske økonomi',
  4: 'Danmark og omverdenen', 5: 'Dansk kulturliv', 6: 'Temaopslag',
};

const sitting = (tag) => {
  const [year, month] = tag.split('#')[0].split('-');
  return `${Number(month) > 8 ? 'vinter' : 'sommer'} ${year}`;
};

/**
 * Facts age. A question is only ever true as of the day it was set, so the
 * panel says when it was asked and warns where the world has since moved.
 * Current-affairs questions are dated by definition: in 2020 the answer to
 * "hvilket parti er i regering" was one thing, and Denmark had a Queen rather
 * than a King. Those are shown as history, never as today's answer.
 */
function dating(q) {
  const last = q.seen.map((s) => s.split('#')[0]).sort().at(-1);
  if (q.dated) {
    return `<div class="caution">${WARN}<span>${q.dated}</span></div>`;
  }
  if (q.section === 'aktuelt') {
    return `<div class="caution">${WARN}<span>
      Aktuelt spørgsmål fra <b>${sitting(last)}</b>. Svaret var rigtigt dengang,
      og er ikke nødvendigvis rigtigt i dag. På din prøve handler de fem aktuelle
      spørgsmål om året, du går op. Følg med i danske nyheder.
    </span></div>`;
  }
  return '';
}

function buildWhy(q, right) {
  const relic = RELICS[state.run.i % RELICS.length];
  const times = q.seen.length;
  const where = q.chapter
    ? `Kapitel ${q.chapter}, ${CHAPTERS[q.chapter]}${q.page ? `, side ${q.page}` : ''}.`
    : '';

  // Three tiers, in order of how much they teach. A written explanation first.
  // Failing that, the sentence from the læremateriale that states the answer,
  // quoted with its page. Restating the answer teaches nothing and is not an
  // option: the green highlight already said it.
  const body = q.explain
    ? `<p>${q.explain}</p>`
    : q.supports && q.passage
      ? `<blockquote>${q.passage}</blockquote>
         <p class="cite">Fra <b>Læremateriale til Indfødsretsprøven</b>, side ${q.page}.</p>`
      : `<p class="thin">Der er endnu ikke skrevet en forklaring til dette spørgsmål.
           Slå det efter i lærematerialet${q.page ? `, side ${q.page}` : ''}.</p>`;

  const why = document.createElement('div');
  why.className = 'why';
  why.innerHTML = `
    <p class="lbl">${relic.svg}${right ? relic.label : 'Det rigtige svar'}</p>
    ${body}
    ${dating(q)}
    <span class="src">
      ${times > 1
        ? `Stillet <b>${times} gange</b> siden 2020: ${q.seen.map(sitting).join(', ')}.`
        : `Stillet <b>${sitting(q.seen[0])}</b>.`}
      ${where}
      Officielt spørgsmål og retteark fra SIRI.
    </span>`;
  return why;
}

function next() {
  const run = state.run;
  if (run.i >= run.questions.length - 1) return finish();
  run.i++;
  renderQuestion();
}

/* ---------- result ---------- */
function finish() {
  const { mode, questions, marks } = state.run;
  const score = marks.filter(Boolean).length;
  const valuesIdx = questions.map((q, i) => (q.section === 'vaerdier' ? i : -1)).filter((i) => i >= 0);
  const valuesScore = valuesIdx.filter((i) => marks[i]).length;

  let passed = null;
  let gate = '';
  if (mode.exam) {
    const okTotal = score >= RULES.pass;
    const okValues = valuesScore >= RULES.valuesPass;
    passed = okTotal && okValues;
    gate = `<div class="gate ${okValues ? 'ok' : 'no'}">
      Værdispørgsmål: <b>${valuesScore} af ${RULES.values}</b> rigtige.
      ${okValues
        ? 'Kravet om mindst 4 er opfyldt.'
        : 'Kravet er mindst 4. Uden det dumper du prøven, uanset din samlede score.'}
    </div>`;
    if (okTotal && !okValues) {
      gate += `<p class="note">Du havde nok rigtige i alt, men værdikravet er en selvstændig hurdle.
        Det er præcis dér, folk falder.</p>`;
    }
  } else if (mode.gate) {
    passed = score >= mode.gate.need;
  } else if (mode.hall) {
    // Decided here, with the other verdicts, so the label below sees it.
    passed = score / questions.length >= HALL_PASS;
  }

  const label = mode.exam
    ? (passed ? 'Bestået' : 'Ikke bestået')
    : (passed === null ? 'Gennemført' : passed ? 'Bestået' : 'Ikke bestået');

  state.best[mode.id] = Math.max(state.best[mode.id] ?? 0, score);
  // Clearing a hall opens the next one, and only ever forwards.
  if (mode.hall && passed) {
    state.cleared = Math.max(state.cleared ?? 0, mode.index + 1);
  }
  save();
  if (passed !== false) sfx.done();

  $('resultCard').innerHTML = `
    <p class="lead">${mode.da}</p>
    <div class="score ${passed === false ? 'fail' : 'pass'}">${score} / ${questions.length}</div>
    <p class="verdict">${label}</p>
    ${gate}
    ${mode.hall
      ? `<p class="note">${passed
          ? 'Hallen er ryddet. Den næste har åbnet sig.'
          : `Du skal have ${Math.ceil(questions.length * HALL_PASS)} af ${questions.length} for at rydde hallen. Spørgsmålene blandes hver gang.`}</p>`
      : mode.exam
      ? `<p class="note">Til den rigtige prøve skal du have ${RULES.pass} af ${RULES.total} rigtige.</p>`
      : `<p class="note">${score === questions.length
          ? 'Fejlfrit. Tag Altinget, når du er klar til hele prøven.'
          : 'Gennemgå de forkerte, og tag den igen. Spørgsmålene blandes hver gang.'}</p>`}
    <div class="actions">
      <button class="btn primary" id="againBtn" type="button">Prøv igen</button>
      <button class="btn ghost" id="backPathBtn" type="button">Tilbage til vejen</button>
    </div>`;

  $('hudMeta').textContent = '';
  go('viewResult', sceneFor(mode));
  $('againBtn').onclick = () => start(mode.id, mode);
  $('backPathBtn').onclick = () => { renderPath(); go('viewPath', 'path'); };
  state.run = null;
}

/* ============================================================
   Boot
   ============================================================ */
async function main() {
  scenes.mount($('scene'));
  load();

  const [questions, explanations] = await Promise.all([
    fetch('./data/questions.jsonl').then((r) => r.text()),
    fetch('./data/explanations.jsonl').then((r) => (r.ok ? r.text() : '')).catch(() => ''),
  ]);

  const why = new Map(
    explanations.split('\n').filter(Boolean)
      .map((l) => JSON.parse(l)).map((e) => [e.id, e]));

  state.bank = questions.split('\n').filter(Boolean).map((line) => {
    const q = JSON.parse(line);
    const extra = why.get(q.id);
    // Hand-written fields win over generated ones (a human-checked page
    // citation beats the located guess), but never the identity.
    return extra ? { ...q, ...extra, id: q.id } : q;
  });

  renderShore();
  if (state.guide) choose(state.guide);
  $('soundToggle').textContent = state.sound ? 'Lyd til' : 'Lyd fra';
  $('soundToggle').setAttribute('aria-pressed', String(state.sound));

  scenes.show('shore');
  $('boot').hidden = true;
}

/* ---------- wiring ---------- */
function begin() {
  if (!state.guide) return;
  renderPath();
  go('viewPath', 'path');
}

$('beginBtn').addEventListener('click', begin);
$('changeGuide').addEventListener('click', () => go('viewShore', 'shore'));
$('modes').addEventListener('click', (e) => {
  const btn = e.target.closest('.mode');
  if (btn) start(btn.dataset.id);
});
$('halls').addEventListener('click', (e) => {
  const btn = e.target.closest('.body:not([disabled])');
  if (!btn) return;
  const i = Number(btn.dataset.i);
  start(null, hallMode(HALLS[i], i));
});
$('quizNext').addEventListener('click', next);
$('quizExit').addEventListener('click', () => { state.run = null; renderPath(); go('viewPath', 'path'); });
$('hudBack').addEventListener('click', () => { state.run = null; renderPath(); go('viewPath', 'path'); });
$('soundToggle').addEventListener('click', (e) => {
  state.sound = !state.sound;
  e.target.textContent = state.sound ? 'Lyd til' : 'Lyd fra';
  e.target.setAttribute('aria-pressed', String(state.sound));
  save();
  tone(600, 0.1);
});
$('resetBtn').addEventListener('click', () => {
  if (!confirm('Nulstil al fremgang?')) return;
  localStorage.removeItem(SAVE);
  location.reload();
});

main().catch((err) => {
  $('boot').innerHTML = `<p>Kunne ikke hente spørgsmålene.<br><small>${err}</small></p>`;
});
