/* ============================================================
   Félag · app shell.

   Data comes from data/questions.jsonl, generated by
   tools/content.py from SIRI's published papers and answer keys.
   Explanations are joined by id from data/explanations.jsonl so
   regenerating the bank can never destroy hand-written work.
   ============================================================ */

import { CAST, byId } from './cast.js';
import * as scenes from './scenes.js';
import * as saga from './map.js';

const $ = (id) => document.getElementById(id);

/* ============================================================
   Where progress lives

   On the device and nowhere else. There is no server, no account
   and nothing transmitted, so the only real risk is a shared
   machine: a family laptop, a library or a jobcenter computer,
   where one browser profile would otherwise mean one shared
   record that the next person inherits and overwrites.

   So progress is namespaced per person on that device. A guest
   writes to sessionStorage instead, which the browser discards
   when the tab closes and leaves nothing behind on a public
   computer.

   localStorage is the right store at this size. The whole record
   is a few hundred bytes, and IndexedDB would be machinery for
   nothing.
   ============================================================ */
const ROSTER = 'felag.people';
const ACTIVE_PROFILE = 'felag.active';
const LEGACY = 'felag.v1';
const keyFor = (slug) => `felag.v1.${slug}`;
const slugify = (name) =>
  name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9æøå-]/g, '').slice(0, 32);

const store = () => (state.profile?.guest ? sessionStorage : localStorage);

function people() {
  try { return JSON.parse(localStorage.getItem(ROSTER) ?? '[]'); } catch { return []; }
}
function remember(list) {
  try { localStorage.setItem(ROSTER, JSON.stringify(list)); } catch { /* ignore */ }
}
function activePerson() {
  const slug = localStorage.getItem(ACTIVE_PROFILE);
  return people().find((name) => slugify(name) === slug) ?? null;
}

/* ---------- exam rules, straight from SIRI ----------
   45 questions: 35 from the læremateriale, 5 current affairs,
   5 on Danish values. Pass needs 36 correct AND at least 4 of
   the 5 values questions. The values gate fails people who
   otherwise scored well, so it is modelled explicitly. */
const RULES = { total: 45, pass: 36, values: 5, valuesPass: 4, minutes: 45 };

/**
 * The next sitting, as SIRI publishes it. Two sittings a year, in May/June and
 * November/December, and the dates for the following year appear on their page
 * by 1 October. So this needs updating roughly twice a year, and the whole
 * card refuses to draw once the date is past rather than counting downwards
 * into the negative: a confidently wrong date here costs somebody a year and a
 * fee, so no card is the safe failure.
 * Source: https://danskogproever.dk/tilmeldingsfrister-og-proevedatoer/
 */
const EXAM = {
  date: '2026-11-25',
  checked: '2026-08-13',
  source: 'https://danskogproever.dk/tilmeldingsfrister-og-proevedatoer/',
};
/* Ungraded crossings keep a little drama. Graded crossings sink only when a
   pass is mathematically impossible; ending earlier would change SIRI's rules. */
const SINK_SHARE = 6 / 45;
const sinkAfter = (n) => Math.max(2, Math.round(n * SINK_SHARE));
const SINK_AFTER_VALUE_WRONG = 2;
const NUMERAL = ['Nul', 'Én', 'To', 'Tre', 'Fire', 'Fem', 'Seks', 'Syv', 'Otte', 'Ni', 'Ti'];

const state = {
  guide: null,
  bank: [],
  best: {},
  hallStats: {},
  battles: [],
  sound: false,
  run: null,
};
let welcomeHall = null;

/* ============================================================
   Persistence
   ============================================================ */
function load() {
  Object.assign(state, { guide: null, best: {}, hallStats: {}, battles: [], cleared: 0, sound: false });
  if (!state.profile) return;
  try {
    Object.assign(state, JSON.parse(store().getItem(state.profile.key) ?? '{}'));
  } catch { /* corrupt or blocked storage is not worth a crash */ }
}
function save() {
  if (!state.profile) return;
  try {
    store().setItem(state.profile.key, JSON.stringify({
      guide: state.guide, best: state.best, hallStats: state.hallStats, battles: state.battles,
      sound: state.sound, cleared: state.cleared,
    }));
  } catch { /* private mode: run without persistence rather than fail */ }
}

/* ============================================================
   Deterministic shuffling

   Option order is randomised so nobody learns "the answer is C".
   That matters here: across the 13 published papers C is correct
   39.3% of the time on three-option questions where chance says
   33.3%, so fixed order teaches a position habit instead of the
   content. The shuffle is seeded so a given run is reproducible,
   which is what later makes shared ghost battles fair.
   ============================================================ */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const hash = (s) => [...s].reduce((h, c) => Math.imul(h ^ c.charCodeAt(0), 16777619), 2166136261);

function shuffle(list, rand) {
  const out = [...list];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function present(entry, seed) {
  // ponytail: Ja/Nej keeps its natural order. With two options, knowing "Ja"
  // already is knowing the content, so shuffling only makes the UI feel wrong.
  const yesNo = entry.options.length === 2 && entry.options.every((o) => /^(Ja|Nej)$/.test(o));
  const options = yesNo ? entry.options : shuffle(entry.options, rng(hash(entry.id + seed)));
  return { ...entry, options, answerAt: options.indexOf(entry.answer) };
}

/* ============================================================
   Sound: synthesised, no audio files ship with this
   ============================================================ */
let audio = null;
function tone(freq, dur = 0.12, type = 'sine', gain = 0.05) {
  if (!state.sound) return;
  audio ??= new (window.AudioContext ?? window.webkitAudioContext)();
  const osc = audio.createOscillator();
  const amp = audio.createGain();
  osc.type = type;
  osc.frequency.value = freq;
  amp.gain.setValueAtTime(gain, audio.currentTime);
  amp.gain.exponentialRampToValueAtTime(0.0001, audio.currentTime + dur);
  osc.connect(amp).connect(audio.destination);
  osc.start();
  osc.stop(audio.currentTime + dur);
}
const sfx = {
  hit: () => { tone(660, 0.1); setTimeout(() => tone(990, 0.16), 70); },
  miss: () => tone(150, 0.22, 'triangle', 0.04),
  done: () => [523, 659, 784].forEach((f, i) => setTimeout(() => tone(f, 0.3), i * 110)),
  sink: () => [220, 174, 130].forEach((f, i) => setTimeout(() => tone(f, 0.3, 'triangle', 0.06), i * 140)),
};

/* ============================================================
   The six halls

   The six chapters of the læremateriale, in order, supplying the
   35 questions of the paper that are drawn from it. You practise
   as you study: clear a hall and the next opens. Nothing is
   locked forever, and the tests below stay open from the start,
   so the gate paces the study without ever barring the door.
   ============================================================ */
const HALL_PASS = 0.8;   // the real paper needs 36 of 45, the same ratio

/* Drawn rather than typed. The old markup used a tick entity and bare words,
   which sat badly next to everything else and could not take the accent colour. */
const ICON = {
  shut: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round">
    <rect x="3" y="7" width="10" height="7" rx="1.6"/><path d="M5.5 7V5a2.5 2.5 0 0 1 5 0v2"/></svg>`,
  open: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round">
    <rect x="3" y="7" width="10" height="7" rx="1.6"/><path d="M5.5 7V5a2.5 2.5 0 0 1 4.9-.6"/></svg>`,
  done: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
    <path d="M3.2 8.4 6.4 11.6 12.8 4.8"/></svg>`,
  chevron: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
    <path d="M4 6.5 8 10.5 12 6.5"/></svg>`,
  book: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
    <path d="M2 3c2-.8 4-.5 6 1v9c-2-1.5-4-1.8-6-1V3Zm12 0c-2-.8-4-.5-6 1v9c2-1.5 4-1.8 6-1V3Z"/></svg>`,
};

/* One visual vocabulary from map to question. The same emblem follows a topic
   into the hall and onto every question drawn from its pages. */
const TOPIC = {
  viking: ['Vikingetid', `<path d="M3 15c3 2 6 3 9 3s6-1 9-3l-2 4H5l-2-4Z"/><path d="M12 3v10m0-8c3 0 5 2 5 4-3 0-5-1-5-4ZM5 12V9"/>`],
  medieval: ['Middelalder', `<path d="M5 20V8h3V4h3v4h2V4h3v4h3v12H5Z"/><path d="M9 20v-5h6v5M8 11h2m4 0h2"/>`],
  crown: ['Konge og enevælde', `<path d="m4 8 4 4 4-7 4 7 4-4-2 11H6L4 8Z"/><path d="M7 16h10"/>`],
  war: ['Krig og grænser', `<path d="m6 19 12-14m-12 0 12 14M4 4l4 1-3 3-1-4Zm16 0-4 1 3 3 1-4Z"/>`],
  industry: ['Industri og bevægelser', `<path d="M4 20V10l5 3V8l5 3V5h4v15H4Z"/><path d="M7 17h2m3 0h2m2 0h2"/>`],
  modern: ['Det moderne Danmark', `<path d="M12 3v18M4 12h16M7 7l10 10m0-10L7 17"/>`],
  democracy: ['Styreformen', `<path d="M4 20h16M6 17h12M7 9h10v8H7V9Zm-2 0 7-5 7 5"/>`],
  constitution: ['Grundloven', `<path d="M6 3h10l3 3v15H6V3Z"/><path d="M16 3v4h4M9 11h7m-7 4h7"/>`],
  parliament: ['Folketinget', `<path d="M3 20h18M5 17h14M7 17V9h10v8M6 9l6-5 6 5"/>`],
  justice: ['Retssamfundet', `<path d="M12 3v18M7 6h10M6 8l-3 6h6L6 8Zm12 0-3 6h6l-3-6ZM8 21h8"/>`],
  welfare: ['Velfærd', `<path d="M12 20S4 15 4 9a4 4 0 0 1 7-2l1 1 1-1a4 4 0 0 1 7 2c0 6-8 11-8 11Z"/>`],
  business: ['Erhvervsliv', `<path d="M4 20V8h16v12H4Zm4-12V5h8v3M4 13h16M10 13v2h4v-2"/>`],
  labour: ['Arbejdsmarked', `<path d="M4 14h16v7H4v-7Zm3 0V9h10v5M9 9V5h6v4"/>`],
  europe: ['Danmark i Europa', `<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18m0-18c-3 3-3 15 0 18"/>`],
  globe: ['Globalt samarbejde', `<circle cx="12" cy="12" r="9"/><path d="m7 7 3 1 1 3 4 1 2 4-3 3-5-2-2-4-3-2"/>`],
  defence: ['Forsvar og sikkerhed', `<path d="M12 3 5 6v6c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="M12 7v10M8 12h8"/>`],
  book: ['Litteratur', `<path d="M4 5c3-1 6 0 8 2v14c-2-2-5-3-8-2V5Zm16 0c-3-1-6 0-8 2v14c2-2 5-3 8-2V5Z"/>`],
  art: ['Billedkunst', `<path d="M12 3a9 9 0 1 0 0 18h2a2 2 0 0 0 0-4h-1a2 2 0 0 1 0-4h4a4 4 0 0 0 4-4c0-4-4-6-9-6Z"/><circle cx="8" cy="9" r="1"/><circle cx="12" cy="7" r="1"/>`],
  music: ['Musik', `<path d="M9 18V7l10-2v11M9 18a3 3 0 1 1-3-3h3m10 1a3 3 0 1 1-3-3h3"/>`],
  architecture: ['Arkitektur', `<path d="M4 21h16M6 18h12M7 18V9h10v9M5 9l7-6 7 6M10 18v-5h4v5"/>`],
  stage: ['Scenekunst', `<path d="M4 4c5 0 8 2 8 7 0 5-3 8-8 9V4Zm16 0c-5 0-8 2-8 7 0 5 3 8 8 9V4Z"/><path d="M7 9h2m6 0h2M7 14c1 1 2 1 3 0m4 0c1 1 2 1 3 0"/>`],
  film: ['Film', `<rect x="3" y="6" width="18" height="14" rx="2"/><path d="M3 10h18M7 6l3 4m2-4 3 4m2-4 3 4"/>`],
  land: ['Land og steder', `<path d="M4 20 8 9l4 4 4-8 4 15H4Z"/><path d="M3 20h18"/>`],
  flag: ['Flaget', `<path d="M6 22V3m1 2h12l-2 4 2 4H7V5Z"/><path d="M11 5v8M7 8h12"/>`],
  realm: ['Rigsfællesskabet', `<circle cx="8" cy="10" r="4"/><circle cx="16" cy="10" r="4"/><circle cx="12" cy="16" r="4"/>`],
  grundtvig: ['Grundtvig og skole', `<path d="M5 19V6h11l3 3v10H5Z"/><path d="M16 6v4h4M8 13h8m-8 3h6"/><path d="m4 4 2-2 2 2"/>`],
  equality: ['Ligestilling og familie', `<circle cx="8" cy="8" r="4"/><circle cx="16" cy="8" r="4"/><path d="M8 12v9m-4-4h8m4-5v9m-4-4h8"/>`],
  health: ['Sundhed', `<path d="M12 21S4 16 4 10a4 4 0 0 1 7-2l1 1 1-1a4 4 0 0 1 7 2c0 6-8 11-8 11Z"/><path d="M8 13h2l1-3 2 6 1-3h2"/>`],
  climate: ['Klima', `<path d="M19 5C11 5 6 9 6 15c0 3 2 6 6 6 6 0 9-7 7-16Z"/><path d="M5 21c2-6 6-9 12-12"/>`],
};

const topicIcon = (key, className = '') => {
  const topic = TOPIC[key] ?? TOPIC.modern;
  return `<svg class="topic-icon ${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${topic[1]}</svg>`;
};

const topicLabel = (key) => (TOPIC[key] ?? TOPIC.modern)[0];

/* The numbers below are the læremateriale's own section starts, so they move
   whenever SIRI reissues it — every August. The August 2026 edition grew from
   243 to 246 pages and pushed every section from 1.7 onwards down by one, and
   everything from 6.7 onwards down by three. Get these wrong and a question
   keeps its hall but lands under the wrong settlement and the wrong emblem,
   which is silent: nothing throws, the page just files Grønland under Norden. */
function topicKey(question) {
  const page = question.page ?? 0;
  if (question.section === 'vaerdier') return 'justice';
  if (question.section === 'aktuelt') return 'modern';
  if (question.chapter === 1) {
    if (page <= 9) return 'viking';
    if (page <= 12) return 'medieval';
    if (page <= 18) return 'crown';
    if (page <= 26) return 'war';
    if (page <= 37) return 'industry';
    return 'modern';
  }
  if (question.chapter === 2) return page < 96 ? 'democracy' : 'justice';
  if (question.chapter === 3) return page < 114 ? 'welfare' : page < 117 ? 'business' : 'labour';
  if (question.chapter === 4) return page < 131 ? 'europe' : page < 136 ? 'globe' : 'defence';
  if (question.chapter === 5) return page < 153 ? 'book' : page < 158 ? 'art' : page < 161 ? 'music' : page < 164 ? 'architecture' : page < 168 ? 'stage' : 'film';
  if (page < 190) return 'land';
  if (page < 191) return 'flag';
  if (page < 193) return 'crown';
  if (page < 208) return 'realm';
  if (page < 229) return 'grundtvig';
  if (page < 238) return 'equality';
  if (page < 242) return 'health';
  return 'climate';
}

const HALLS = [
  { numeral: 'I', chapter: 1, accent: '--thor', da: 'Danmarks historie', en: "Denmark's history",
    topics: ['viking', 'medieval', 'crown', 'war', 'industry', 'modern'] },
  { numeral: 'II', chapter: 2, accent: '--gorm', da: 'Det danske demokrati', en: 'Danish democracy',
    topics: ['democracy', 'constitution', 'parliament', 'justice'] },
  { numeral: 'III', chapter: 3, accent: '--ingrid', da: 'Den danske økonomi', en: 'The Danish economy',
    topics: ['welfare', 'business', 'labour'] },
  { numeral: 'IV', chapter: 4, accent: '--freja', da: 'Danmark og omverdenen', en: 'Denmark and the world',
    topics: ['europe', 'globe', 'defence'] },
  { numeral: 'V', chapter: 5, accent: '--astrid', da: 'Dansk kulturliv', en: 'Danish cultural life',
    topics: ['book', 'art', 'music', 'architecture', 'stage', 'film'] },
  { numeral: 'VI', chapter: 6, accent: '--bjorn', da: 'Temaopslag', en: 'Thematic entries',
    topics: ['land', 'flag', 'crown', 'realm', 'grundtvig', 'equality', 'health', 'climate'] },
];

const inChapter = (n) =>
  state.bank.filter((q) => q.section === 'laeremateriale' && q.chapter === n && usable(q));

/**
 * Where a hall stands on the road: cleared behind you, open in front of you,
 * or still shut. The gate paces the study, so this rule decides what can be
 * entered and it must say the same thing everywhere. The list, the summary
 * meter on the path and the saga map all ask here rather than each deriving
 * it from `cleared` again.
 */
const hallState = (i, cleared = state.cleared ?? 0) =>
  i < cleared ? 'done' : i === cleared ? 'open' : 'shut';

function hallProgress(hall) {
  const stock = inChapter(hall.chapter);
  const ids = new Set(stock.map((q) => q.id));
  const progress = state.hallStats?.[hall.chapter] ?? {};
  const seen = new Set((progress.seen ?? []).filter((id) => ids.has(id))).size;
  const correct = new Set((progress.correct ?? []).filter((id) => ids.has(id))).size;
  return { total: stock.length, seen, correct, left: stock.length - seen };
}

function hallMode(hall, index) {
  const stock = inChapter(hall.chapter);
  return {
    id: `hal-${hall.chapter}`,
    da: `Hal ${hall.numeral}. ${hall.da}`,
    accent: hall.accent,
    hall, index,
    build: (rand) => weighted(stock, Math.min(12, stock.length), rand),
  };
}

function renderHalls() {
  const cleared = state.cleared ?? 0;
  $('halls').innerHTML = HALLS.map((hall, i) => {
    const gate = hallState(i, cleared);
    const shut = gate === 'shut';
    const done = gate === 'done';
    const progress = hallProgress(hall);
    const mark = ICON[done ? 'done' : shut ? 'shut' : 'open'];
    const label = done ? 'Port åbnet' : shut ? 'Låst' : 'Åben';
    const { places } = sagaCounts(hall.chapter);
    return `<div class="hall ${done ? 'done' : ''} ${shut ? 'shut' : ''}"
        style="--accent:var(${hall.accent}); --d:${i * 0.06}s">
        <span class="thread"></span>
        <span class="node">${done ? ICON.done : hall.numeral}</span>
        <span class="hall-main">
        <button class="body" type="button" data-i="${i}" ${shut ? 'disabled' : ''}>
          <span class="names">
           <span class="da">${hall.da}</span>
            <span class="en">${hall.en}</span>
            <span class="state">${mark}${label}</span>
          </span>
          <span class="chips">${hall.topics.map((key) => `<span>${topicIcon(key)}${topicLabel(key)}</span>`).join('')}
            <span>${progress.total} spørgsmål</span></span>
          <span class="hall-progress"><span>Set <b>${progress.seen}</b></span><span>Rigtige <b>${progress.correct}</b></span><span>Tilbage <b>${progress.left}</b></span></span>
        </button>
        <!-- Never disabled, whatever the gate says. The lock is on sitting the
             hall, not on reading the chapter, and a locked hall is exactly where
             somebody is standing when they most need the way in to the reading.
             Given the same width as the hall's own board, because a reading room
             that is always open should not be advertised in smaller type than
             the door that is shut. -->
        <button class="hall-read" type="button" data-read="${i}">
          <span class="read-mark" aria-hidden="true">${ICON.book}</span>
          <span class="read-copy">
            <b>Læs sagaen om ${inSentence(hall.da)}</b>
            <small>${places} ${places === 1 ? 'bebyggelse' : 'bebyggelser'} &middot; altid åben</small>
          </span>
          <svg class="read-go" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m10 5 7 7-7 7m6-7H6"/></svg>
        </button>
        </span>
      </div>`;
  }).join('');
}

function renderLearningPath() {
  const cleared = Math.min(state.cleared ?? 0, HALLS.length);
  const next = HALLS[cleared];
  $('learningPath').innerHTML = `
    <span class="learning-sigil" aria-hidden="true"><svg viewBox="0 0 64 56" fill="none"><path d="M7 45c10-18 18-27 27-27 8 0 12 8 23 8"/><path d="m49 17 8 9-10 6"/><circle cx="8" cy="45" r="4"/><circle cx="20" cy="31" r="3"/><circle cx="33" cy="18" r="3"/><circle cx="46" cy="25" r="3"/></svg></span>
    <span class="learning-copy"><span class="learning-kicker">Læringsstien</span><b>De Seks Haller</b>
      <small>${cleared === HALLS.length ? 'Alle seks porte er åbnet.' : `Næste hal: ${next.da}`}</small>
      <span class="learning-meter" aria-label="${cleared} af ${HALLS.length} porte åbnet">${HALLS.map((_, i) => `<i class="${hallState(i, cleared)}"></i>`).join('')}<em>${cleared} / ${HALLS.length} porte åbnet</em></span>
    </span>
    <span class="learning-open">Åbn stien<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m10 5 7 7-7 7m6-7H6"/></svg></span>`;
}

function renderWelcomeJourney() {
  const cleared = state.profile ? state.cleared ?? 0 : 0;
  const current = Math.min(cleared, HALLS.length - 1);
  document.querySelectorAll('[data-welcome-hall]').forEach((button) => {
    const index = Number(button.dataset.welcomeHall);
    const hall = HALLS[index];
    const status = index < cleared ? 'ryddet' : index === cleared ? 'åben' : 'låst';
    button.classList.toggle('done', index < cleared);
    button.classList.toggle('active', index === current);
    button.disabled = index > cleared;
    button.setAttribute('aria-label', `Hal ${hall.numeral}: ${hall.da}, ${status}`);
  });
  $('welcomeIdentity').textContent = state.profile ? `Fortsæt som ${state.profile.name}` : 'Begynd her';
  $('welcomeHallName').textContent = HALLS[current].da;
  $('welcomeStart').querySelector('span').textContent = state.profile ? 'Fortsæt rejsen' : 'Begynd vandringen';
  $('welcomeNavStart').textContent = state.profile ? 'Fortsæt' : 'Start træning';
}

/* ============================================================
   Modes
   ============================================================ */
const MODES = [
  {
    id: 'ovelse', da: 'Øvelse', en: 'Practice', accent: '--freja', icon: 'grundtvig',
    blurb: 'Tilfældige spørgsmål fra lærematerialet, vægtet efter hvor ofte SIRI faktisk har stillet dem.',
    tag: 'Ubegrænset', training: true,
    build: (rand) => weighted(pool('laeremateriale'), 15, rand),
  },
  {
    id: 'dyst', da: 'Dysten', en: 'The duel', accent: '--bjorn', icon: 'defence',
    blurb: 'Ro om kap med Bjørn over 15 spørgsmål. Båden flytter sig efter rigtige svar, ikke efter tid, så det er præcision der afgør det.',
    tag: 'Mod Bjørn',
    duel: true,
    build: (rand) => weighted(pool('laeremateriale'), 15, rand),
  },
  {
    id: 'tid', da: 'Tidslinjen', en: 'The timeline', accent: '--astrid', icon: 'viking',
    blurb: 'Danmarks historie fra vikingetiden til i dag, periode for periode. Det største kapitel og det, der fylder mest på prøven.',
    tag: '12 perioder',
    teaches: 'time',
  },
  {
    id: 'ting', da: 'Tinget', en: 'The values assembly', accent: '--ingrid', icon: 'justice',
    blurb: 'De 5 værdispørgsmål. Du skal have mindst 4 rigtige, ellers dumper du hele prøven uanset resten. Lær principperne først.',
    tag: 'Kræver 4 af 5',
    teaches: true, ting: true,
    build: (rand) => pick(pool('vaerdier'), RULES.values, rand),
    gate: { need: RULES.valuesPass, of: RULES.values },
  },
  {
    id: 'alting', da: 'Altinget', en: 'The full assembly', accent: '--thor', icon: 'parliament',
    blurb: 'Hele prøven under rigtige regler: 45 spørgsmål, 36 for at bestå, og mindst 4 af 5 værdispørgsmål.',
    tag: '45 spørgsmål',
    build: (rand) => [
      ...pick(pool('laeremateriale'), 35, rand),
      // Only the freshest current-affairs questions, and even those are
      // labelled. On the day, these five will be about your own year.
      ...pick(recent(pool('aktuelt')), 5, rand),
      ...pick(pool('vaerdier'), 5, rand),
    ],
    exam: true,
  },
];

const DESTINATIONS = [
  {
    id: 'sagaer', da: 'Sagaerne', en: 'The reading rooms', accent: '--gorm', icon: 'book',
    blurb: 'Lærematerialets 243 sider som noget, der kan læses: hvert kapitel lagt ud efter hvor meget der bliver spurgt om siderne.',
    tag: 'Aldrig låst',
  },
  {
    id: 'training', da: 'Træning', en: 'Practice routes', accent: '--freja', icon: 'grundtvig',
    blurb: 'Øvelse, Tidslinjen og Tinget samlet ét sted. Vælg det, du vil træne.', tag: '3 træningsrum',
  },
  {
    id: 'dyst', da: 'Dysten', en: 'The battle', accent: '--bjorn', icon: 'defence',
    blurb: 'Mål dig mod Bjørn eller en dansk viking i de samme 15 spørgsmål.', tag: 'Kampplads',
  },
  {
    id: 'alting', da: 'Altinget', en: 'The full test', accent: '--thor', icon: 'parliament',
    blurb: 'Hele prøven under de rigtige regler: 45 spørgsmål, 36 for at bestå.', tag: '45 spørgsmål',
  },
  {
    id: 'heim', da: 'Vikingheim', en: 'The settlement', accent: '--astrid', icon: 'architecture',
    blurb: 'Bopladsen i tre dimensioner. Ingen spørgsmål, ingen prøve, bare et sted at hvile øjnene.',
    tag: 'Et pusterum',
  },
];

function modeCard(mode, index) {
  const best = state.best[mode.id];
  return `<button class="mode" type="button" data-id="${mode.id}"
      style="--accent:var(${mode.accent}); --d:${index * 0.08}s">
      <h3>${topicIcon(mode.icon, `mode-icon ${mode.id}`)}${mode.da} ${best ? `<span class="best">bedste ${best}</span>` : ''}</h3>
      <span class="en">${mode.en}</span>
      <p>${mode.blurb}</p>
      <span class="tag">${mode.tag}</span>
    </button>`;
}

/** Each mode keeps its own place, including on the result screen. */
const sceneFor = (mode) => (mode.ting ? 'ting' : mode.exam ? 'alting' : 'hall');

/** The hall list and the saga map are two doors into the same six rooms, so
    a hall returns through whichever one it was entered by. */
let hallDoor = showHalls;

/** Sagaerne is reachable from the hall list and from the path, so leaving a
    reading room goes back the way it was entered rather than always to one. */
let sagaDoor = showHalls;

/** Leaving a drill returns where it was started from, not to the map. */
const leave = (mode) => mode?.hall ? hallDoor()
  : mode?.training ? showTraining()
  : mode?.ting ? showTing()
  : mode?.time ? showTime()
  : mode?.duel ? showArena()
  : (renderPath(), go('viewPath', 'path'));

/**
 * Outdated questions never enter a draw.
 *
 * A wrong answer presented as current is the worst thing this project can do,
 * so anything hand-checked and found stale is excluded outright rather than
 * shown with a caveat. "Hvilket politisk parti er i regering?" answered
 * Socialdemokratiet in 2020; since 2022 it has been an S, V and M coalition.
 *
 * Current-affairs questions never repeat between papers (0 of 65), so drilling
 * them teaches facts that were true on one afternoon years ago. They are kept
 * out of practice entirely and appear only in the full mock, where the paper's
 * shape matters and each is labelled with the sitting it came from.
 */
const usable = (q) => q.status !== 'outdated';

const pool = (section) => state.bank.filter((q) => q.section === section && usable(q));
function pick(list, n, rand) {
  const out = [];
  const stems = new Set();
  for (const question of shuffle(list, rand)) {
    if (stems.has(question.stem)) continue;
    stems.add(question.stem);
    out.push(question);
    if (out.length === Math.min(n, list.length)) break;
  }
  return out;
}

/** The newest sittings only; older current-affairs answers have moved on. */
function recent(list) {
  const latest = (q) => q.seen.map((s) => s.split('#')[0]).sort().at(-1);
  const newest = list.map(latest).sort().at(-1) ?? '';
  const cutoff = String(Number(newest.slice(0, 4)) - 1);
  return list.filter((q) => latest(q) >= cutoff);
}

/** Frequency-weighted draw: questions SIRI asks often come up more.
    Takes the run's own generator, so the same seed always yields the same paper
    and two people can be given an identical one. */
function weighted(list, n, rand) {
  const bag = list.flatMap((q) => Array(Math.min(q.seen.length, 4)).fill(q));
  const out = [];
  const taken = new Set();
  const stems = new Set();
  let guard = 0;
  while (out.length < Math.min(n, list.length) && bag.length && guard++ < 5000) {
    const q = bag[Math.floor(rand() * bag.length)];
    if (!taken.has(q.id) && !stems.has(q.stem)) {
      taken.add(q.id);
      stems.add(q.stem);
      out.push(q);
    }
  }
  return out;
}

/* ============================================================
   Views
   ============================================================ */
const VIEWS = ['viewWho', 'viewShore', 'viewPath', 'viewTraining', 'viewHalls', 'viewSagaer', 'viewSagas', 'viewMap', 'viewHeim', 'viewTime', 'viewArena', 'viewTing', 'viewQuiz', 'viewResult'];
function go(id, scene) {
  const swap = () => {
    // The counter and clock belong to a run; nothing else should inherit them.
    if (id !== 'viewQuiz') $('hudMeta').textContent = '';
    // Vikingheim holds a WebGL context and a render loop. Every route out of
    // it runs through here, so tearing it down here is the only place that
    // cannot be forgotten later.
    if (id !== 'viewHeim') heim?.dispose();
    VIEWS.forEach((v) => { $(v).hidden = v !== id; });
    if (scene) scenes.show(scene);
    $('hud').hidden = id === 'viewShore' || id === 'viewWho' || id === 'viewPath';
    scrollTo({ top: 0, behavior: 'instant' });
  };
  // Native view transitions; browsers without it simply get the swap.
  document.startViewTransition ? document.startViewTransition(swap) : swap();
}

/* ---------- who is studying ---------- */
const escape = (t) => t.replace(/[&<>"']/g, (c) =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function renderPeople() {
  const list = people();
  $('profiles').innerHTML = list.map((name, i) => {
    const safe = escape(name);
    let done = 0;
    try { done = JSON.parse(localStorage.getItem(keyFor(slugify(name))) ?? '{}').cleared ?? 0; }
    catch { /* ignore */ }
    return `<span class="profile-row">
        <button class="profile" type="button" data-name="${safe}" style="--d:${i * 0.05}s">
          <span class="mark">${safe.slice(0, 1).toUpperCase()}</span>
          <span><b>${safe}</b><small>${done ? `${done} af 6 porte åbnet` : 'ingen porte åbnet endnu'}</small></span>
        </button>
        <button class="drop" type="button" data-drop="${safe}" aria-label="Fjern ${safe}">&times;</button>
      </span>`;
  }).join('');
  $('newProfile').querySelector('input').placeholder = list.length ? 'Nyt navn' : 'Dit navn';
}

function resumeJourney() {
  if (!state.profile) return showWho();
  if (!state.guide) return go('viewShore', 'shore');
  const hallIndex = welcomeHall;
  welcomeHall = null;
  if (hallIndex !== null && hallState(hallIndex) !== 'shut') {
    return start(null, hallMode(HALLS[hallIndex], hallIndex));
  }
  renderPath();
  go('viewPath', 'path');
}

function useProfile(name, { guest = false } = {}) {
  state.profile = guest
    ? { name: 'Gæst', slug: 'gaest', key: 'felag.guest', guest: true }
    : { name, slug: slugify(name), key: keyFor(slugify(name)), guest: false };
  load();
  if (!guest) localStorage.setItem(ACTIVE_PROFILE, state.profile.slug);
  $('foot').hidden = false;
  $('whoNow').textContent = state.profile.name;
  $('soundToggle').textContent = state.sound ? 'Lyd til' : 'Lyd fra';
  $('soundToggle').setAttribute('aria-pressed', String(state.sound));
  renderShore();
  if (state.pendingChallenge) {
    const challenge = state.pendingChallenge;
    state.pendingChallenge = null;
    const mode = modeById(challenge.modeId);
    if (mode) return start(mode.id, mode, { ...challenge, name: 'Vikingen' });
  }
  if (state.guide) {
    choose(state.guide);
    return resumeJourney();
  }
  go('viewShore', 'shore');
}

function showWho() {
  $('foot').hidden = true;
  renderPeople();
  go('viewWho', 'landfall');
}

/* ---------- shore ---------- */
function renderShore() {
  $('roster').innerHTML = CAST.map((c, i) => `
    <button class="char" type="button" data-id="${c.id}" aria-pressed="false"
      style="--accent:var(${c.accent}); --d:${i * 0.07}s">
      <figure>${c.svg}</figure>
      <b>${c.name}</b><span>${c.style}</span>
    </button>`).join('');

}

function choose(id) {
  const c = byId(id);
  state.guide = id;
  save();
  document.querySelectorAll('.char').forEach((el) =>
    el.setAttribute('aria-pressed', String(el.dataset.id === id)));
  const banner = $('banner');
  banner.style.setProperty('--accent', `var(${c.accent})`);
  banner.innerHTML = `
    <span class="banner-name" style="color:var(${c.accent})">${c.name} &middot; ${c.style}</span>
    <span class="banner-line">&ldquo;${c.quote}&rdquo;</span>
    <span class="banner-strength">${c.strength}</span>`;
  $('beginBtn').disabled = false;
  tone(520, 0.09);
}

/* ---------- path ---------- */
function renderPath() {
  const c = byId(state.guide) ?? CAST[0];
  $('walker').innerHTML = c.svg;
  $('guideName').textContent = c.name;
  $('pathSub').textContent = c.recommends;

  renderLearningPath();
  $('modes').innerHTML = DESTINATIONS
    .filter((d) => d.id !== 'heim' || heimWelcome())
    .map(modeCard).join('');
  renderExamDate();
}

/* Whole calendar days from today to an ISO date, counted on the day boundary
   rather than on the clock, so "i morgen" does not become "i dag" at 23:59. */
function daysTo(iso) {
  const now = new Date();
  const today = Date.UTC(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((Date.parse(`${iso}T00:00:00Z`) - today) / 86400000);
}

function renderExamDate() {
  const left = daysTo(EXAM.date);
  // Past its own date it knows only that it is out of date, so it stops
  // counting and points at the table that is still right.
  if (left < 0) {
    $('examDate').innerHTML = `<em>Næste prøvedato offentliggøres af
      <a href="${EXAM.source}" target="_blank" rel="noopener">SIRI</a>.</em>`;
    return;
  }
  // No weekday: it is one more word between you and the date itself.
  const when = new Intl.DateTimeFormat('da-DK', { day: 'numeric', month: 'long', year: 'numeric' })
    .format(new Date(`${EXAM.date}T00:00:00Z`));
  $('examDate').innerHTML = `
    <span class="landing-boat" aria-hidden="true">${BOAT}</span>
    <b>${left === 0 ? 'I dag' : `${left} ${left === 1 ? 'dag' : 'dage'}`}</b>
    <em>${left === 0
      ? 'Indfødsretsprøven er i dag.'
      : `til Indfødsretsprøven · den ${when}`}</em>`;
}

function showTraining() {
  $('hudTitle').textContent = 'Træning';
  $('hudBackLabel').textContent = 'Tilbage til vejen';
  $('hudBack').setAttribute('aria-label', 'Tilbage til vejen');
  $('hudBack').dataset.tooltip = 'Tilbage til vejen';
  $('trainingSigil').innerHTML = topicIcon('book');
  $('trainingModes').innerHTML = MODES.filter((mode) => mode.training || mode.teaches).map(modeCard).join('');
  go('viewTraining', 'path');
}

function showHalls() {
  hallDoor = showHalls;
  $('hudTitle').textContent = 'De Seks Haller';
  $('hudBackLabel').textContent = 'Tilbage til vejen';
  $('hudBack').setAttribute('aria-label', 'Tilbage til vejen');
  $('hudBack').dataset.tooltip = 'Tilbage til vejen';
  renderHalls();
  go('viewHalls', 'path');
}

/* ============================================================
   Sagaerne · the reading room

   The drill asks; the saga tells. Nothing in here is written for
   the room: every question already carries the answer SIRI gave,
   a hand-written explanation and the page it was drawn from, so
   a saga is that same material laid out to be read rather than
   answered. Inventing prose for a study aid that promises "kun
   svar der er givet" is the one thing this project must not do.

   It is never gated. The six halls lock to pace the drilling; a
   free study aid that refuses to let you read chapter four until
   you have passed chapter three would be a strange thing to ship.

   A saga is drawn as a settlement, and how big the settlement is
   comes from how many of the exam's questions were drawn from
   those pages. That is not decoration: the material is steeply
   uneven, six stretches hold a quarter of the paper, and 98 of
   the 243 pages have never been examined at all. Those stand as
   ødegårde, the word for a farm left empty after the plague. The
   pages are there and nobody lives on them, which is worth more
   to somebody studying against a clock than a footnote would be.
   ============================================================ */

const PLACES = [
  { from: 20, kind: 'by', da: 'By',
    glyph: `<path d="M3 21h18M5 21V9l4-3 4 3v12M13 21v-9l3-2 3 2v9"/><path d="M7 12h2m-2 3h2m8-1h2m-2 3h2"/>` },
  { from: 12, kind: 'kobstad', da: 'Købstad',
    glyph: `<path d="M3 21h18M5 21v-8l4-3 4 3v8"/><path d="M15 21v-9l3-2 3 2v9M18 7V4m-1.5 1.5h3"/>` },
  { from: 6, kind: 'landsby', da: 'Landsby',
    glyph: `<path d="M3 21h18M6 21v-6l3-2 3 2v6M14 21v-4l3-2 3 2v4"/>` },
  { from: 1, kind: 'gaard', da: 'Gård',
    glyph: `<path d="M3 21h18M5 21v-7l7-4 7 4v7"/><path d="M10 21v-5h4v5"/>` },
  { from: 0, kind: 'oede', da: 'Ødegård',
    glyph: `<path d="M3 21h18"/><path d="M6 21v-6l3-2 1 .6M18 21v-5l-2-1.4" stroke-dasharray="2.6 2.2"/><path d="M13 21v-2.5"/>` },
];

const placeOf = (n) => PLACES.find((p) => n >= p.from);

const sagasIn = (chapter) => (state.sagas ?? []).filter((s) => s.chapter === chapter);

/**
 * What a chapter's reading actually amounts to, counted the way the room counts.
 *
 * Not `saga.questions.length`: that is the raw membership, before answers that
 * have gone out of date are dropped and before questions teaching one fact are
 * folded together. Advertising 129 on the door and showing 108 inside is the
 * kind of small lie that costs trust in everything else on the page.
 */
function sagaCounts(chapter) {
  const stretches = sagasIn(chapter).map((saga) =>
    oneEach(saga.questions.map((id) => state.bankById.get(id)).filter((q) => q && usable(q))));
  return {
    places: stretches.filter((s) => s.length).length,
    readings: stretches.reduce((n, s) => n + s.length, 0),
    pages: sagasIn(chapter).reduce((n, s) => n + (s.until - s.page + 1), 0),
  };
}

/** A hall's name dropped into the middle of a sentence. "Det danske demokrati"
    has to lose its capital there and "Danmarks historie" has to keep it, which
    is the whole of the rule: proper noun stays, everything else is an adjective
    or a common noun and goes down. */
const inSentence = (name) =>
  name.startsWith('Danmark') ? name : name[0].toLowerCase() + name.slice(1);

/**
 * Collapse questions that teach one fact into a single reading.
 *
 * The bank keys a question on its stem *and* its options, because SIRI reuses a
 * stem with a different option set and a different correct answer. Two option
 * sets are two exercises, so that is right for drilling and wrong here: with it,
 * Vikingetid printed "Freja og Thor" twice, once for 2024 and once for 2026 with
 * one distractor swapped, and told you each had been asked once.
 *
 * Which wording leads is decided by which carries the fullest explanation, and
 * the whole entry comes from that one question — never a sentence from one and
 * an answer from another. The count is unioned over the members actually shown,
 * so "stillet 3 gange" is a claim the page can back up.
 */
function oneEach(questions) {
  const taken = new Set();
  const out = [];
  for (const q of questions) {
    const group = state.kin?.get(q.id);
    if (!group) { out.push(q); continue; }
    if (taken.has(group)) continue;
    taken.add(group);
    const kin = group.map((id) => state.bankById.get(id)).filter((x) => x && usable(x));
    if (!kin.length) continue;
    const lead = kin.reduce((best, x) =>
      (x.explain?.length ?? 0) > (best.explain?.length ?? 0) ? x : best, kin[0]);
    const asked = [...new Set(kin.flatMap((x) => x.seen))].sort();
    out.push({ ...lead, seen: asked });
  }
  return out;
}

/** One question, laid out to be read: the answer leads, the explanation
    carries it, and SIRI's own wording is kept as the provenance underneath.

    Several explanations open by restating the answer, which reads fine under a
    quiz card that has not said it yet and reads as a stutter under a heading
    that just did. The heading has already said it, so the repeat comes off —
    but only when the answer is a whole sentence of its own. Where the answer is
    the subject the sentence goes on to use, cutting it leaves a fragment:
    "Susanne Bier instruerede Hævnen" becomes "Instruerede Hævnen", and "Nuuk,
    tidligere kaldet Godthåb" becomes a comma with nothing in front of it. A
    full stop after the answer is the only safe seam, and it covers 242 of the
    327 that repeat; the other 85 are left exactly as they were written. */
function told(q, missed) {
  const times = q.seen.length;
  const lead = q.answer.replace(/\.$/, '');
  let why = q.explain ?? '';
  if (why.toLowerCase().startsWith(lead.toLowerCase()) && why[lead.length] === '.') {
    why = why.slice(lead.length + 1).trim() || why;
  }
  return `<article class="told ${missed ? 'missed' : ''}">
      <p class="told-a">${q.answer}${missed ? '<em>du missede den</em>' : ''}</p>
      ${why ? `<p class="told-why">${why}</p>` : ''}
      <p class="told-src">Spurgt: &ldquo;${q.q}&rdquo;
        &middot; ${q.page ? materialLink(q.page) : ''}
        &middot; ${times === 1 ? 'stillet én gang' : `stillet ${times} gange`}</p>
    </article>`;
}

/**
 * The chapter as a road of settlements, largest meaning most examined.
 *
 * `missed` is the set of question ids just got wrong, which is the whole point
 * of the room: failing a hall opens the places those questions came from and
 * nothing else, so the reading is aimed at the gap rather than at the chapter.
 */
/**
 * The six chapters as reading rooms, with no gate on any of them.
 *
 * The hall list next door is about drilling and has to show a lock; this is the
 * same six rooms with the lock taken off, because it is the way in for somebody
 * who came to read rather than to be tested.
 */
function showSagaer() {
  sagaDoor = showSagaer;
  $('hudTitle').textContent = 'Sagaerne';
  const back = 'Tilbage til vejen';
  $('hudBackLabel').textContent = back;
  $('hudBack').setAttribute('aria-label', back);
  $('hudBack').dataset.tooltip = back;

  $('sagaHalls').innerHTML = HALLS.map((hall, i) => {
    const { places, readings, pages } = sagaCounts(hall.chapter);
    return `<div class="hall" style="--accent:var(${hall.accent}); --d:${i * 0.06}s">
        <span class="thread"></span>
        <span class="node">${hall.numeral}</span>
        <span class="hall-main">
          <button class="body" type="button" data-read="${i}">
            <span class="names">
              <span class="da">${hall.da}</span>
              <span class="en">${hall.en}</span>
              <span class="state">${ICON.book}Læs</span>
            </span>
            <span class="hall-progress">
              <span>Bebyggelser <b>${places}</b></span>
              <span>Spørgsmål <b>${readings}</b></span>
              <span>Sider <b>${pages}</b></span>
            </span>
          </button>
        </span>
      </div>`;
  }).join('');
  go('viewSagaer', 'path');
}

function showSagas(hall, missed = null) {
  const places = sagasIn(hall.chapter);
  const shown = places.map((saga) => {
    const questions = oneEach(
      saga.questions.map((id) => state.bankById.get(id)).filter((q) => q && usable(q)));
    const hit = missed ? questions.filter((q) => missed.has(q.id)) : questions;
    return { saga, questions, hit };
  }).filter((row) => !missed || row.hit.length);

  $('hudTitle').textContent = `Sagaen · ${hall.da}`;
  const back = 'Tilbage til De Seks Haller';
  $('hudBackLabel').textContent = back;
  $('hudBack').setAttribute('aria-label', back);
  $('hudBack').dataset.tooltip = back;
  $('sagasTitle').textContent = `Sagaen om ${inSentence(hall.da)}`;

  const total = shown.reduce((n, row) => n + row.hit.length, 0);
  $('sagasSub').innerHTML = missed
    ? `Du missede <b>${total}</b> ${total === 1 ? 'spørgsmål' : 'spørgsmål'} i
       ${shown.length} ${shown.length === 1 ? 'bebyggelse' : 'bebyggelser'}.
       Læs dem her, og tag hallen igen når du er klar.`
    : `Kapitlet ligger som ${places.length} bebyggelser langs vejen. Jo større stedet,
       jo mere er der spurgt om de sider. Alt er åbent fra første dag &mdash;
       det her er læsestof, ikke en prøve.`;

  $('places').innerHTML = shown.map(({ saga, questions, hit }, i) => {
    const place = placeOf(questions.length);
    const open = missed || shown.length === 1 ? 'open' : '';
    // One settlement at a time, so a chapter is a page you read rather than a
    // mile you scroll. `name` on <details> is the browser's own accordion and
    // needs no script; where it is not supported the panels simply stay
    // independent, which is what they were before.
    //
    // Not in focus mode. There the room is already only the questions you got
    // wrong, so there is nothing to shorten and everything to compare.
    const group = missed ? '' : `name="saga-${hall.chapter}"`;
    return `<div class="place ${place.kind}" style="--accent:var(${hall.accent}); --d:${i * 0.05}s">
        <span class="thread"></span>
        <span class="node" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"
          stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
          stroke-linejoin="round">${place.glyph}</svg></span>
        <details class="body" ${group} ${open}>
          <summary>
            <span class="names">
              <span class="da">${saga.title}</span>
              <span class="state">${place.da}${ICON.chevron}</span>
            </span>
            <span class="place-meta">
              <span>${questions.length ? `${questions.length} spørgsmål` : 'aldrig spurgt om'}</span>
              <span>side ${saga.page}${saga.until > saga.page ? `\u2013${saga.until}` : ''}</span>
              ${missed ? `<span class="lost">${hit.length} du missede</span>` : ''}
            </span>
            ${saga.covers.length
              ? `<span class="covers">Rummer også ${saga.covers.join(' &middot; ')}</span>`
              : ''}
          </summary>
          ${hit.length
            ? hit.map((q) => told(q, missed?.has(q.id))).join('')
            : `<p class="told-none">Ingen af prøvens spørgsmål er hentet herfra i de tretten
               prøver siden 2020. Siderne er værd at kende, men de er ikke det, du falder på.</p>`}
        </details>
      </div>`;
  }).join('');

  go('viewSagas', 'hall');
}

/* ---------- the saga map ---------- */

const GATE_LABEL = { done: 'Ryddet', open: 'Åben', shut: 'Låst' };

/**
 * The eight stops, in the order they are walked.
 *
 * The halls are gated: clear one and the next opens. The two assemblies are
 * not, and must never be drawn as though they were. The papers have been open
 * from the first day on purpose, so that someone sitting the test next week
 * can go straight to it without first grinding six halls they have no time
 * for. A locked Alting would be a lie about how this project works.
 */
function stops() {
  const cleared = state.cleared ?? 0;
  const assembly = (id, kind) => {
    const mode = MODES.find((m) => m.id === id);
    const gate = state.best[id] ? 'done' : 'open';
    return {
      kind, name: mode.da, accent: mode.accent, gate,
      state: GATE_LABEL[gate],
      aria: `${mode.da}, ${mode.en}. ${GATE_LABEL[gate]}. Altid åben.`,
    };
  };
  return [
    ...HALLS.map((hall, i) => {
      const gate = hallState(i, cleared);
      return {
        kind: 'hall', numeral: hall.numeral, name: hall.da, accent: hall.accent, gate,
        state: GATE_LABEL[gate],
        aria: `Hal ${hall.numeral}, ${hall.da}. ${GATE_LABEL[gate]}.`,
      };
    }),
    assembly('ting', 'ting'),
    assembly('alting', 'alting'),
  ];
}

/* ---------- Vikingheim ---------- */

/**
 * Vikingheim is scenery, and it costs about 700 KB of WebGL library to draw.
 *
 * That is a bad trade to make on someone else's behalf, so it is only offered
 * when all three of these hold: the reader has not asked for less motion, the
 * connection has not been flagged as metered, and there is a screen wide
 * enough to be worth it. When it is not offered it is not merely disabled,
 * it is absent — an offer you cannot take is worse than no offer.
 */
const heimWelcome = () => !scenes.still.matches
  && !navigator.connection?.saveData
  && innerWidth >= 760
  && innerHeight >= 520;

let heim = null;

async function showHeim() {
  $('hudTitle').textContent = 'Vikingheim';
  $('hudBackLabel').textContent = 'Tilbage til vejen';
  $('hudBack').setAttribute('aria-label', 'Tilbage til vejen');
  $('hudBack').dataset.tooltip = 'Tilbage til vejen';
  go('viewHeim', 'shore');
  try {
    heim ??= await import('./heim.js');
    heim.mount($('heim'));
  } catch {
    // A settlement that will not build is not worth an error message. Say
    // where it went, leave the road open, and never let it break the path.
    $('heim').innerHTML = '<p class="heim-absent">Bopladsen kunne ikke bygges her. Vejen og hallerne virker som altid.</p>';
  }
}

function showMap() {
  hallDoor = showMap;
  $('hudTitle').textContent = 'Kortet';
  $('hudBackLabel').textContent = 'Tilbage til vejen';
  $('hudBack').setAttribute('aria-label', 'Tilbage til vejen');
  $('hudBack').dataset.tooltip = 'Tilbage til vejen';
  saga.render($('map'), stops(), state.guide, (i) => {
    if (i < HALLS.length) return start(null, hallMode(HALLS[i], i));
    // The Ting teaches its principles before it tests them, the same as it
    // does from the path; the map is another door into the room, not a
    // shortcut past it.
    return i === HALLS.length ? showTing() : start('alting');
  });
  go('viewMap', 'path');
}

/* ---------- Arena ---------- */
const RESULT_MARK = {
  won: `<svg viewBox="0 0 24 24" fill="none"><path d="M12 3 5 6v6c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="m8 12 3 3 5-6"/></svg>`,
  lost: `<svg viewBox="0 0 24 24" fill="none"><path d="M12 3 5 6v6c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="m9 9 6 6m0-6-6 6"/></svg>`,
  draw: `<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9"/><path d="M7 12h10"/></svg>`,
};

/**
 * The banner you sail home under. Raised on a spear when the throne holds,
 * struck and torn from a broken staff when it does not, and furled around the
 * shaft when neither side took the field. Drawn rather than lettered, because
 * you should be able to tell how it went from across the room.
 */
const BANNER = {
  won: `<svg viewBox="0 0 76 76" fill="none" aria-hidden="true">
    <path class="banner-gust" d="M60 21h10M62 30h9M60 39h10" stroke="#d3a24c" stroke-width="2.6" stroke-linecap="round" opacity=".3"/>
    <path d="M16 2 21 12h-10l5-10Z" fill="#d3a24c"/>
    <path d="M16 10v60" stroke="#d3a24c" stroke-width="3.4" stroke-linecap="round"/>
    <path class="banner-cloth" d="M17 14h39l-9 13 9 13H17Z" fill="#c8102e"/>
    <path class="banner-cloth" d="M31 14v26M17 27h30" stroke="#efe3c8" stroke-width="5"/>
    <path d="M4 70h26" stroke="#d3a24c" stroke-width="3" stroke-linecap="round" opacity=".5"/>
  </svg>`,
  lost: `<svg viewBox="0 0 76 76" fill="none" aria-hidden="true">
    <path d="M14 70 19 44" stroke="#7d6a4e" stroke-width="3.4" stroke-linecap="round"/>
    <path d="m21 40 6-22" stroke="#7d6a4e" stroke-width="3.4" stroke-linecap="round"/>
    <path class="banner-cloth" d="M28 17h33l-7 12 6 12-9-6-6 10-7-9-8 8Z" fill="#7e3427"/>
    <path class="banner-cloth" d="M42 18v22M29 27h27" stroke="#9c8a6e" stroke-width="5"/>
    <path d="M4 70h30" stroke="#7d6a4e" stroke-width="3" stroke-linecap="round" opacity=".45"/>
  </svg>`,
  draw: `<svg viewBox="0 0 76 76" fill="none" aria-hidden="true">
    <path d="M20 6v64M56 6v64" stroke="#8fae8c" stroke-width="3.4" stroke-linecap="round"/>
    <path class="banner-cloth" d="M21 16h14v20l-7-6-7 6Z" fill="#8fae8c" opacity=".85"/>
    <path class="banner-cloth" d="M41 16h14v20l-7-6-7 6Z" fill="#8fae8c" opacity=".85"/>
    <path d="M4 70h68" stroke="#8fae8c" stroke-width="3" stroke-linecap="round" opacity=".45"/>
  </svg>`,
};

/** What the hall shouts when you walk back in. */
const DUEL_CRY = (result, them) => ({
  won: ['Sejr', 'Du beholder din trone, viking!', `${them} ror hjem med tom snekke. Skjoldtavlen har fået et mærke mere.`],
  lost: ['Nederlag', 'Er du sikker på, du er viking?', `${them} tog tronen. Slib øksen, og kræv den tilbage.`],
  draw: ['Uafgjort', 'Ingen tog tronen i dag.', `Skjold mod skjold. Du og ${them.toLowerCase()} nåede land på samme åretag.`],
}[result]);

/* The feed opens on the last ten and grows on request. Old duels are worth
   keeping, but nobody arrives at the arena wanting to read thirty of them. */
const BATTLE_PAGE = 10;
let battlesShown = BATTLE_PAGE;

function showArena() {
  $('hudTitle').textContent = 'Dysten';
  $('arenaBjorn').innerHTML = byId('bjorn').svg;
  battlesShown = BATTLE_PAGE;
  renderBattles();
  go('viewArena', 'hall');
}

function renderBattles() {
  const battles = state.battles ?? [];
  const won = battles.filter((battle) => battle.result === 'won').length;
  const lost = battles.filter((battle) => battle.result === 'lost').length;
  const drawn = battles.filter((battle) => battle.result === 'draw').length;
  const total = battles.length;
  const rate = total ? Math.round((won / total) * 100) : 0;
  const stats = [
    ['won', 'Sejre', won], ['lost', 'Tabt', lost], ['draw', 'Uafgjort', drawn],
  ];
  $('battleForm').textContent = total ? `${rate}% sejrsrate` : 'Klar til kamp';
  $('battleRecord').innerHTML = `
    <div class="record-hero ${total ? '' : 'empty'}">
      <span class="record-shield">${RESULT_MARK.won}</span>
      <span><small>${total ? 'Din sejrsrate' : 'Dit første mærke'}</small><b>${total ? `${rate}%` : 'Klar'}</b><em>${total ? `${won} af ${total} kampe vundet` : 'Vælg en modstander og sæt sejl.'}</em></span>
    </div>
    ${stats.map(([result, label, count]) => `<span class="record-total ${result}" aria-label="${count} ${label.toLowerCase()}">${RESULT_MARK[result]}<b>${count}</b><small>${label}</small></span>`).join('')}`;
  const shown = Math.min(battlesShown, total);
  const rest = total - shown;
  $('battleList').innerHTML = total
    ? `<p class="match-feed-title">Skjoldtavlen · ${total} ${total === 1 ? 'kamp' : 'kampe'}</p>${battles.slice(0, shown).map((battle) => `
      <div class="match ${battle.result}">
        <span class="match-mark">${RESULT_MARK[battle.result]}</span>
        <span><b>Mod ${escape(battle.opponent)}</b><small>${battle.date}</small></span>
        <span class="match-score" aria-label="${battle.mine} mod ${battle.theirs}"><b>${battle.mine}</b><i>–</i><b>${battle.theirs}</b></span>
        <em>${battle.result === 'won' ? 'Vundet' : battle.result === 'lost' ? 'Tabt' : 'Uafgjort'}</em>
      </div>`).join('')}
      ${rest ? `<button class="match-more" id="battleMore" type="button">Rul tavlen længere tilbage · ${rest} ${rest === 1 ? 'kamp' : 'kampe'} mere</button>` : ''}`
    : `<div class="scoreboard-empty">${RESULT_MARK.won}<span><b>Skjoldtavlen venter.</b> Vælg Bjørn eller kast handsken til en dansk viking.</span></div>`;
  const more = document.getElementById('battleMore');
  if (more) more.onclick = () => { battlesShown += BATTLE_PAGE; renderBattles(); };
}

function recordBattle(opponent, mine, theirs, sunk) {
  const result = mine > theirs ? 'won' : mine < theirs ? 'lost' : 'draw';
  state.battles = [{
    opponent,
    mine,
    theirs,
    result,
    sunk: Boolean(sunk),
    date: new Intl.DateTimeFormat('da-DK', { day: 'numeric', month: 'short' }).format(new Date()),
  }, ...(state.battles ?? [])].slice(0, 30);
  return result;
}

/* ---------- Tidslinjen ---------- */
function showTime() {
  $('hudTitle').textContent = 'Tidslinjen';
  $('hudBackLabel').textContent = 'Tilbage til Træning';
  $('hudBack').setAttribute('aria-label', 'Tilbage til Træning');
  $('hudBack').dataset.tooltip = 'Tilbage til Træning';
  const most = Math.max(...state.eras.map((e) => e.questions.length), 1);

  $('eras').innerHTML = state.eras.map((era, i) => {
    const stock = era.questions.filter((id) => usable(byQuestion(id))).length;
    // An open end means two different things: the last period is still running,
    // an earlier one simply starts around then and overlaps its neighbours.
    const span = era.to ? `${era.from}\u2013${era.to}`
      : i === state.eras.length - 1 ? `${era.from}\u2013` : `fra ${era.from}`;
    const years = era.to ? `${era.to - era.from} år` : (i === state.eras.length - 1 ? 'til i dag' : '');
    return `<div class="era" style="--d:${i * 0.05}s">
        <span class="knot"></span>
        <span class="axis"><b>${span}</b><span>${years}</span></span>
        <button class="body" type="button" data-i="${i}" ${stock ? '' : 'disabled'}>
          <h4>${topicIcon(topicKey({ chapter: 1, page: era.page }))}${era.title}</h4>
          <span class="weight">
            <i style="width:${Math.round((stock / most) * 100)}px"></i>
            <span>${stock ? `${stock} spørgsmål` : 'ingen spørgsmål'}</span>
          </span>
        </button>
      </div>`;
  }).join('');
  go('viewTime', 'path');
}

const byQuestion = (id) => state.bank.find((q) => q.id === id) ?? {};

/** A drill on one period of history. */
function eraMode(era) {
  const stock = era.questions.map(byQuestion).filter((q) => q.id && usable(q));
  return {
    id: `tid-${era.page}`, da: era.title, accent: '--astrid', time: true,
    build: (rand) => weighted(stock, Math.min(12, stock.length), rand),
  };
}

/* ---------- Tinget ---------- */
function showTing() {
  $('hudTitle').textContent = 'Tinget';
  $('hudBackLabel').textContent = 'Tilbage til Træning';
  $('hudBack').setAttribute('aria-label', 'Tilbage til Træning');
  $('hudBack').dataset.tooltip = 'Tilbage til Træning';
  $('principles').innerHTML = state.principles.map((p, i) => `
    <div class="principle" data-id="${p.id}" style="--d:${i * 0.05}s">
      <button type="button" aria-expanded="false">
        <h4><span class="n">${String(i + 1).padStart(2, '0')}</span>${p.title}
          <span class="count">${p.questions.length} spørgsmål</span>
          <span class="chev">${ICON.chevron}</span></h4>
        <p class="rule">${p.rule}</p>
      </button>
    </div>`).join('');
  go('viewTing', 'ting');
}

function togglePrinciple(el) {
  const open = el.classList.toggle('open');
  el.querySelector('button').setAttribute('aria-expanded', String(open));
  el.querySelector('.more')?.remove();
  if (!open) return;

  const p = state.principles.find((x) => x.id === el.dataset.id);
  const more = document.createElement('div');
  more.className = 'more';
  more.innerHTML = `<p>${p.detail}</p>
    <button class="btn primary" type="button" data-practice="${p.id}">
      Øv ${p.questions.length} spørgsmål</button>`;
  el.append(more);
}

/** A drill on one principle, drawn only from the questions it explains. */
function principleMode(p) {
  const stock = state.bank.filter((q) => p.questions.includes(q.id) && usable(q));
  return {
    id: `princip-${p.id}`, da: p.title, accent: '--ingrid', ting: true,
    build: (rand) => shuffle(stock, rand),
  };
}

/* ---------- quiz ---------- */
/* A rowing boat, oars out. Not a longship under sail: you are the one pulling. */
const BOAT = `<svg viewBox="0 0 38 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <g class="oars" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" opacity=".85">
    <path d="M13 17 4 11"/><path d="M25 17l9-6"/>
  </g>
  <g class="hull">
    <path d="M6 18c2.4 3.1 7.4 4.4 13 4.4S29.6 21.1 32 18c-3.6 1.4-8.2 1.9-13 1.9S9.6 19.4 6 18Z" fill="currentColor"/>
    <path d="M6.4 17.9C4.6 16.7 4 14.2 5.1 12c.7 1.8 1.8 3.2 3.2 4.3-.7.6-1.3 1.1-1.9 1.6Z" fill="currentColor"/>
    <path d="M31.6 17.9c1.8-1.2 2.4-3.7 1.3-5.9-.7 1.8-1.8 3.2-3.2 4.3.7.6 1.3 1.1 1.9 1.6Z" fill="currentColor"/>
    <circle cx="19" cy="14.5" r="2.4" fill="currentColor"/>
  </g></svg>`;

function start(modeId, override, ghost) {
  const mode = override ?? MODES.find((m) => m.id === modeId);
  const seed = ghost?.seed ?? (Date.now() >>> 0);
  const questions = mode.build(rng(seed)).map((q) => present(q, seed));
  if (!questions.length) return;

  state.run = {
    mode, seed, questions, i: 0, marks: Array(questions.length).fill(null),
    ghost: ghost ?? null,
    deadline: mode.exam ? Date.now() + RULES.minutes * 60000 : null,
  };
  const returnLabel = mode.hall ? 'Tilbage til De Seks Haller' : 'Tilbage til vejen og hallerne';
  $('hudTitle').textContent = mode.da;
  $('hudBackLabel').textContent = returnLabel;
  $('hudBack').setAttribute('aria-label', returnLabel);
  $('hudBack').dataset.tooltip = returnLabel;
  go('viewQuiz', sceneFor(mode));
  renderQuestion();
  if (state.run.deadline) tick();
}

function tick() {
  const run = state.run;
  if (!run?.deadline) return;
  const left = run.deadline - Date.now();
  if (left <= 0) return finish();
  $('hudMeta').textContent =
    `${String(Math.floor(left / 60000)).padStart(2, '0')}:${String(Math.floor(left / 1000) % 60).padStart(2, '0')}`;
  setTimeout(tick, 1000);
}

/**
 * A challenge is a seed plus a record of who got what right, small enough to
 * live in a link. No server, no accounts: the run rebuilds itself from the seed,
 * so both people are given exactly the same paper in the same order.
 */
const packRun = (run) => [
  run.mode.id, run.seed.toString(36),
  run.marks.map((m) => (m === true ? '1' : m === false ? '0' : 'x')).join(''),
].join('~');

function unpackRun(text) {
  const [id, seed, bits] = (text ?? '').split('~');
  if (!id || !seed || !bits || !/^[01x]+$/.test(bits)) return null;
  return {
    modeId: id,
    seed: parseInt(seed, 36),
    marks: [...bits].map((b) => b === 'x' ? null : b === '1'),
  };
}

/** Rebuild any mode from the id stored in a challenge link. */
function modeById(id) {
  if (id?.startsWith('hal-')) {
    const n = Number(id.slice(4));
    const i = HALLS.findIndex((h) => h.chapter === n);
    return i < 0 ? null : hallMode(HALLS[i], i);
  }
  if (id?.startsWith('tid-')) {
    const era = state.eras.find((e) => e.page === Number(id.slice(4)));
    return era ? eraMode(era) : null;
  }
  if (id?.startsWith('princip-')) {
    const p = state.principles.find((x) => x.id === id.slice(8));
    return p ? principleMode(p) : null;
  }
  return MODES.find((m) => m.id === id) ?? null;
}

/** Bjørn does not need a recorded run: his is derived from the same seed. */
function houseGhost(modeId, seed, accuracy = 0.72) {
  const rand = rng(seed ^ 0x5bd1e995);
  return { modeId, seed, name: 'Bjørn', house: true,
           marks: Array.from({ length: 64 }, () => rand() < accuracy) };
}

/** Advance the crossing. One stroke of the oars per question answered. */
function renderRow(stroke) {
  const { marks, i, ghost } = state.run;
  const row = $('row');
  $('rowTrack').innerHTML = marks
    .map((m) => `<i class="${m === true ? 'hit' : m === false ? 'miss' : ''}"></i>`).join('');
  $('rowBoat').innerHTML = BOAT;
  $('rowGhost').innerHTML = state.run.ghost ? BOAT : '';
  $('rowGhost').hidden = !state.run.ghost;
  // Position is correct answers, not questions seen. The race is on accuracy,
  // which is what the exam actually measures.
  const answered = marks.filter((m) => m !== null).length;
  const mine = marks.filter(Boolean).length;

  // One answer is one pull of the oars. Accuracy belongs in the wake markers;
  // it must not leave the boat frozen at the shore after a wrong answer. Store
  // a plain percentage rather than relying on CSS multiplication, which is not
  // consistent across mobile engines.
  row.style.setProperty('--p', `${2 + (answered / marks.length) * 90}%`);

  if (ghost) {
    const theirs = ghost.marks.slice(0, answered).filter(Boolean).length;
    row.style.setProperty('--g', `${2 + (theirs / marks.length) * 90}%`);
    row.classList.toggle('behind', answered > 0 && mine < theirs);
  }
  row.classList.toggle('sinking', Boolean(state.run.sunk));

  if (!stroke) return;
  row.classList.remove('stroke', 'stumble');
  void row.offsetWidth;                       // restart the animation
  row.classList.add(stroke === 'miss' ? 'stumble' : 'stroke');
}

function renderQuestion() {
  const run = state.run;
  const q = run.questions[run.i];
  const letters = ['A', 'B', 'C'];
  const topic = topicKey(q);

  if (!run.deadline) $('hudMeta').textContent = `${run.i + 1} / ${run.questions.length}`;
  renderRow();
  $('quizNext').disabled = true;
  const nextLabel = run.i === run.questions.length - 1 ? 'Læg til ved land' : 'Sejl videre';
  $('quizNextLabel').textContent = nextLabel;
  $('quizNext').setAttribute('aria-label', nextLabel);
  $('quizNext').dataset.tooltip = nextLabel;

  $('quizCard').innerHTML = `
    <div class="q-topic">${topicIcon(topic)}<span>${topicLabel(topic)}</span></div>
    <p class="q">${q.q}</p>
    ${q.options.map((o, n) => `
      <button class="opt" type="button" data-n="${n}" style="--d:${n * 0.05}s">
        <em>${letters[n]}</em><span>${o}</span>
      </button>`).join('')}`;

  $('quizCard').querySelectorAll('.opt').forEach((btn) =>
    btn.addEventListener('click', () => answer(Number(btn.dataset.n)), { once: true }));
}

function sinkReason(run) {
  const wrong = run.marks.filter((mark) => mark === false).length;
  const pass = run.mode.exam
    ? RULES.pass
    : run.mode.hall
    ? Math.ceil(run.questions.length * HALL_PASS)
    : run.mode.gate?.need;
  const fatal = pass ? run.questions.length - pass + 1 : sinkAfter(run.questions.length);
  if (wrong >= fatal) {
    return `${NUMERAL[wrong] ?? wrong} fejl. Skibet tager for meget vand ind.`;
  }

  const valuesWrong = run.questions
    .filter((question, index) => question.section === 'vaerdier' && run.marks[index] === false)
    .length;
  if (valuesWrong >= SINK_AFTER_VALUE_WRONG) {
    return `To fejl i værdispørgsmålene. Tinget lader dig ikke passere.`;
  }
  return null;
}

function answer(chosen) {
  const run = state.run;
  const q = run.questions[run.i];
  const right = chosen === q.answerAt;
  run.marks[run.i] = right;
  if (run.mode.hall) {
    const progress = (state.hallStats ??= {})[run.mode.hall.chapter] ??= { seen: [], correct: [] };
    if (!progress.seen.includes(q.id)) progress.seen.push(q.id);
    if (right && !progress.correct.includes(q.id)) progress.correct.push(q.id);
    save();
  }
  const sunk = right ? null : sinkReason(run);
  run.sunk = sunk;

  const opts = [...$('quizCard').querySelectorAll('.opt')];
  opts.forEach((b) => { b.disabled = true; });
  opts[q.answerAt].classList.add('hit');
  if (!right) opts[chosen].classList.add('miss');
  right ? sfx.hit() : sunk ? sfx.sink() : sfx.miss();
  renderRow(right ? 'stroke' : 'miss');

  $('quizCard').append(buildWhy(q, right));
  if (sunk) {
    $('quizNext').disabled = true;
    $('quizNextLabel').textContent = 'Skibet synker';
    $('quizNext').setAttribute('aria-label', 'Skibet synker');
    $('quizNext').dataset.tooltip = 'Skibet synker';
    setTimeout(() => finish(), 1200);
    return;
  }
  $('quizNext').disabled = false;
}

const WARN = `<svg viewBox="0 0 24 24" fill="none"><path d="M12 3.5 22 20H2L12 3.5Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M12 10v4M12 17h.01" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>`;

const CHAPTERS = {
  1: 'Danmarks historie', 2: 'Det danske demokrati', 3: 'Den danske økonomi',
  4: 'Danmark og omverdenen', 5: 'Dansk kulturliv', 6: 'Temaopslag',
};

const sitting = (tag) => {
  const [year, month] = tag.split('#')[0].split('-');
  return `${Number(month) > 8 ? 'vinter' : 'sommer'} ${year}`;
};

const MATERIAL_URL = 'laeremateriale-til-indfoedsretsproeven';

/** A citation you can open. Every claim should be checkable against SIRI. */
function paperLink(tag) {
  const [stamp, number] = tag.split('#');
  const url = state.sources?.[`indfoedsretsproeven-${stamp}`];
  const label = sitting(tag);
  return url
    ? `<a href="${url}" target="_blank" rel="noopener">${label}, spørgsmål ${number}</a>`
    : `${label}, spørgsmål ${number}`;
}

function materialLink(page) {
  const url = state.sources?.[MATERIAL_URL];
  const label = `Læremateriale til Indfødsretsprøven, side ${page}`;
  return url ? `<a href="${url}" target="_blank" rel="noopener">${label}</a>` : label;
}

/**
 * Facts age. A question is only ever true as of the day it was set, so the
 * panel says when it was asked and warns where the world has since moved.
 * Current-affairs questions are dated by definition: in 2020 the answer to
 * "hvilket parti er i regering" was one thing, and Denmark had a Queen rather
 * than a King. Those are shown as history, never as today's answer.
 */
function dating(q) {
  const last = q.seen.map((s) => s.split('#')[0]).sort().at(-1);
  if (q.currency || q.dated) {
    return `<div class="caution">${WARN}<span>${q.currency ?? q.dated}</span></div>`;
  }
  if (q.section === 'aktuelt') {
    return `<div class="caution">${WARN}<span>
      Aktuelt spørgsmål fra <b>${sitting(last)}</b>. Svaret var rigtigt dengang,
      og er ikke nødvendigvis rigtigt i dag. På din prøve handler de fem aktuelle
      spørgsmål om året, du går op. Følg med i danske nyheder.
    </span></div>`;
  }
  return '';
}

function buildWhy(q, right) {
  const topic = topicKey(q);
  const times = q.seen.length;
  const where = q.chapter
    ? `Kapitel ${q.chapter}, ${CHAPTERS[q.chapter]}${q.page ? `, side ${q.page}` : ''}.`
    : '';

  // Every values question rests on one of the ten principles, so it can always
  // be answered with the rule behind it rather than with the bare fact. That
  // matters more here than anywhere else: these questions barely repeat, so the
  // principle is the only part worth carrying into the exam.
  const principle = q.section === 'vaerdier'
    ? state.principles.find((p) => p.questions.includes(q.id))
    : null;

  // A raw sentence selected by word overlap is not an explanation. It produced
  // failures such as a 2022 coalition sentence for a 1993 Poul Nyrup question.
  // Only a written explanation or a values principle may teach the answer.
  const body = q.explain
    ? `<p>${q.explain}</p>`
    : principle
    ? `<p><b>${principle.title}.</b> ${principle.rule}</p><p>${principle.detail}</p>`
    : `<p class="thin">Forklaringen bliver skrevet fra lærematerialet${q.page ? `, side ${q.page}` : ''}.</p>`;

  const why = document.createElement('div');
  why.className = 'why';
  why.innerHTML = `
    <p class="lbl">${topicIcon(topic)}Forklaring · ${topicLabel(topic)}</p>
    ${body}
    ${dating(q)}
    <span class="src">
      ${times > 1
        ? `Stillet <b>${times} gange</b> siden 2020: ${q.seen.map(paperLink).join(', ')}.`
        : `Stillet <b>${paperLink(q.seen[0])}</b>.`}
      ${q.page ? `Slå efter i ${materialLink(q.page)}.` : where}
      Åbn den officielle prøve for at se spørgsmålet med de oprindelige svarmuligheder.
    </span>`;
  return why;
}

function next() {
  const run = state.run;
  if (run.i >= run.questions.length - 1) return finish();
  run.i++;
  renderQuestion();
}

/* ---------- result ---------- */
function finish() {
  if (!state.run || state.run.finishing) return;
  state.run.finishing = true;
  const { mode, questions, marks } = state.run;
  const finished = state.run;
  const sunk = state.run.sunk;
  const score = marks.filter(Boolean).length;
  const answered = marks.filter((mark) => mark !== null).length;
  const valuesIdx = questions.map((q, i) => (q.section === 'vaerdier' ? i : -1)).filter((i) => i >= 0);
  const valuesScore = valuesIdx.filter((i) => marks[i]).length;

  let passed = null;
  let gate = '';
  if (mode.exam) {
    const okTotal = score >= RULES.pass;
    const okValues = valuesScore >= RULES.valuesPass;
    passed = okTotal && okValues;
    gate = `<div class="gate ${okValues ? 'ok' : 'no'}">
      Værdispørgsmål: <b>${valuesScore} af ${RULES.values}</b> rigtige.
      ${okValues
        ? 'Kravet om mindst 4 er opfyldt.'
        : 'Kravet er mindst 4. Uden det dumper du prøven, uanset din samlede score.'}
    </div>`;
    if (okTotal && !okValues) {
      gate += `<p class="note">Du havde nok rigtige i alt, men værdikravet er en selvstændig hurdle.
        Det er præcis dér, folk falder.</p>`;
    }
  } else if (mode.gate) {
    passed = score >= mode.gate.need;
  } else if (mode.hall) {
    // Decided here, with the other verdicts, so the label below sees it.
    passed = score / questions.length >= HALL_PASS;
  }
  if (sunk) passed = false;

  const label = sunk
    ? 'Skibet sank'
    : mode.exam
    ? (passed ? 'Bestået' : 'Ikke bestået')
    : (passed === null ? 'Gennemført' : passed ? 'Bestået' : 'Ikke bestået');

  const ghost = state.run.ghost;
  // Over the whole paper, not over the part you reached. Your ship sinking is
  // your problem: it does not shorten the crossing the other one already rowed,
  // and scoring them out of `answered` printed a number nobody could reconcile
  // with the "af 15" next to it.
  const theirs = ghost ? ghost.marks.slice(0, questions.length).filter(Boolean).length : null;
  const rival = ghost?.name ?? 'Vikingen';
  const battleResult = ghost ? recordBattle(rival, score, theirs, sunk) : null;

  state.best[mode.id] = Math.max(state.best[mode.id] ?? 0, score);
  // Clearing a hall opens the next one, and only ever forwards.
  const wasCleared = state.cleared ?? 0;
  if (mode.hall && passed) {
    state.cleared = Math.max(state.cleared ?? 0, mode.index + 1);
  }
  // The prize fires once, at the crossing from "not all" to "all six".
  const wonAll = wasCleared < HALLS.length && state.cleared >= HALLS.length;
  save();
  if (passed !== false) sfx.done();

  // A duel is settled head to head, so the solo score and the neutral
  // "Gennemført" give way to the banner and the two numbers side by side.
  const [cry, shout, aftermath] = ghost ? DUEL_CRY(battleResult, rival) : [];
  const verdict = ghost
    ? `<div class="duel ${battleResult}">
        <span class="duel-banner">${BANNER[battleResult]}</span>
        <p class="duel-cry">${cry}</p>
        <p class="duel-shout">${shout}</p>
        <div class="duel-tally">
          <span class="side"><small>Dig</small><b>${score}</b></span>
          <i aria-hidden="true">–</i>
          <span class="side"><small>${escape(rival)}</small><b>${theirs}</b></span>
        </div>
        <p class="duel-after">${aftermath}</p>
      </div>`
    : `<div class="score ${passed === false ? 'fail' : 'pass'}">${score} / ${questions.length}</div>
       <p class="verdict">${label}</p>`;

  // Failing a hall is the moment the reading is worth most, and the gap is
  // already known precisely: these are the ones just got wrong. The room opens
  // on those pages alone rather than on the whole chapter.
  const missed = mode.hall && passed === false
    ? questions.filter((_, i) => marks[i] === false)
    : [];

  $('resultCard').innerHTML = `
    <p class="lead">${mode.da}</p>
    ${verdict}
    ${sunk ? `<div class="gate no"><b>${sunk}</b> Øv dig, og sæt sejl igen.</div>` : ''}
    ${gate}
    ${ghost
      ? ''
      : mode.hall
      ? `${wonAll ? `<div class="prize">
          <span class="prize-sigil" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none"><path d="M24 4l5 11 12 1-9 8 3 12-11-6-11 6 3-12-9-8 12-1z"/></svg></span>
          <b>Alle seks porte er åbnet!</b>
          <span>Du har gennemført hele Læringsstien og læst hele sagaen. Nu venter Altinget — hele prøven på tid, under de rigtige regler.</span>
          <button class="btn primary prize-go" id="altingBtn" type="button">${topicIcon('parliament', 'mode-icon alting')}Tag Altinget nu — 45 spørgsmål</button>
        </div>` : ''}
        <p class="note">${passed
          ? (wonAll ? 'Den sidste hal er ryddet. Sagaen er fuldført.' : 'Porten er åbnet. Den næste hal kan nu besøges.')
          : sunk
          ? 'Du nåede ikke frem denne gang. Brug forklaringerne og prøv hallen igen.'
          : `Du skal have ${Math.ceil(questions.length * HALL_PASS)} af ${questions.length} for at rydde hallen. Spørgsmålene blandes hver gang.`}</p>`
      : mode.exam
      ? `<p class="note">Til den rigtige prøve skal du have ${RULES.pass} af ${RULES.total} rigtige.</p>`
      : `<p class="note">${score === questions.length
          ? 'Fejlfrit. Tag Altinget, når du er klar til hele prøven.'
          : 'Gennemgå de forkerte, og tag den igen. Spørgsmålene blandes hver gang.'}</p>`}
    ${missed.length ? `<button class="read-back" id="sagaBtn" type="button">
      <span class="read-sigil" aria-hidden="true">${ICON.book}</span>
      <span><b>Læs sagaen om det, du missede</b><small>${missed.length}
        ${missed.length === 1 ? 'spørgsmål' : 'spørgsmål'} · med forklaring og sidehenvisning</small></span>
      <svg class="challenge-arrow" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m10 5 7 7-7 7m6-7H6"/></svg>
    </button>` : ''}
    <div class="actions">
      <button class="btn primary" id="againBtn" type="button"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 11a8 8 0 1 0 2 5M20 4v7h-7"/></svg>${ghost ? (ghost.house ? 'Kræv omkamp' : 'Sejl igen') : 'Få nye spørgsmål'}</button>
      <button class="challenge-btn" id="shareBtn" type="button" data-tooltip="Din danske viking får det samme sæt spørgsmål og kan slå din score.">
        <span class="challenge-sigil" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none"><path d="m11 39 26-30m-26 0 26 30"/><path d="m8 10 9 2-4 8-7-4 2-6Zm32 0-9 2 4 8 7-4-2-6Z" fill="currentColor"/><path d="M24 19v16M17 35h14"/></svg></span>
        <span><b>Udfordr en dansk viking</b><small>Hvem kender Danmark bedst?</small></span>
        <svg class="challenge-arrow" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m10 5 7 7-7 7m6-7H6"/></svg>
      </button>
    </div>
    <p class="share-note" id="shareNote" role="status" aria-live="polite" hidden></p>`;

  $('hudMeta').textContent = '';
  go('viewResult', sceneFor(mode));
  $('againBtn').onclick = () => {
    const freshSeed = Date.now() >>> 0;
    start(mode.id, mode, ghost?.house ? houseGhost(mode.id, freshSeed) : null);
  };
  if (missed.length) {
    $('sagaBtn').onclick = () => {
      sagaDoor = hallDoor;
      showSagas(mode.hall, new Set(missed.map((q) => q.id)));
    };
  }
  if (wonAll) {
    $('altingBtn').onclick = () => start('alting');
  }
  $('shareBtn').onclick = async () => {
    // The whole challenge travels in the fragment, so nothing is stored anywhere.
    const link = `${location.origin}${location.pathname}#dyst=${packRun(finished)}`;
    const note = $('shareNote');
    const tell = (message) => {
      note.hidden = false;
      note.innerHTML = `${RESULT_MARK.won}<span>${message}</span>`;
    };
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Félag: udfordr en dansk viking', text: 'Hvem kender Danmark bedst?', url: link });
        return tell('Dit løb er delt. Glæd dig til modsvaret.');
      } catch (error) {
        if (error.name === 'AbortError') return;
      }
    }
    try {
      await navigator.clipboard.writeText(link);
      tell('Dit løb er klar. Linket er kopieret.');
    } catch {
      prompt('Kopiér dit løb:', link);
    }
  };
  state.run = null;
}

/* ============================================================
   Boot
   ============================================================ */
async function main() {
  scenes.mount($('scene'));
  load();

  const lines = (t) => t.split('\n').filter(Boolean).map((l) => JSON.parse(l));
  const grab = (p) => fetch(p).then((r) => (r.ok ? r.text() : '')).catch(() => '');

  const [questions, explanations, currency, principles, eras, sagaList, kinship, sources] = await Promise.all([
    fetch('./data/questions.jsonl').then((r) => r.text()),
    grab('./data/explanations.jsonl'),
    grab('./data/currency.jsonl'),
    grab('./data/principles.jsonl'),
    grab('./data/eras.jsonl'),
    grab('./data/sagas.jsonl'),
    grab('./data/kinship.jsonl'),
    grab('./data/sources.json'),
  ]);
  state.sources = sources ? JSON.parse(sources) : {};
  state.principles = principles ? lines(principles) : [];
  state.eras = eras ? lines(eras) : [];
  state.sagas = sagaList ? lines(sagaList) : [];
  // Read as id -> the group it belongs to, so a lookup is one step and two
  // members of a group resolve to the very same array and compare identical.
  state.kin = new Map();
  for (const group of kinship ? lines(kinship) : []) {
    // The file also records pairs a human ruled must stay apart, with the
    // reason written beside them. Those are there to stop the question being
    // re-asked on the next rebuild; here they are simply not groups.
    for (const id of group.questions ?? []) state.kin.set(id, group.questions);
  }

  const why = new Map(explanations ? lines(explanations).map((e) => [e.id, e]) : []);
  const age = new Map(currency ? lines(currency).map((e) => [e.id, e]) : []);

  state.bank = lines(questions).map((q) => {
    const extra = why.get(q.id);
    // Hand-written fields win over generated ones (a human-checked page
    // citation beats the located guess), but never the identity.
    const merged = extra ? { ...q, ...extra, id: q.id } : q;
    const now = age.get(q.id);
    return now ? { ...merged, status: now.status, currency: now.note } : merged;
  });
  state.bankById = new Map(state.bank.map((q) => [q.id, q]));
  const papers = new Set(state.bank.flatMap((q) => q.seen.map((seen) => seen.split('#')[0])));
  $('welcomeQuestions').textContent = state.bank.length.toLocaleString('da-DK');
  $('welcomeQuestionCopy').textContent = `${state.bank.length.toLocaleString('da-DK')} rigtige spørgsmål`;
  $('welcomePapers').textContent = papers.size.toLocaleString('da-DK');
  $('welcomeHalls').textContent = HALLS.length.toLocaleString('da-DK');

  // Anyone who used the app before profiles existed keeps their progress.
  const legacy = localStorage.getItem(LEGACY);
  if (legacy && !people().length) {
    localStorage.setItem(keyFor('mig'), legacy);
    remember(['Mig']);
    localStorage.removeItem(LEGACY);
  }

  // A challenge link carries everything needed to replay the same paper.
  const challenge = unpackRun(new URLSearchParams(location.hash.slice(1)).get('dyst'));
  if (challenge) {
    history.replaceState(null, '', location.pathname);
    state.pendingChallenge = challenge;
  }
  const active = activePerson();
  if (active) useProfile(active);
  else showWho();
  renderWelcomeJourney();
  if (challenge && active) $('welcome').hidden = true;
  else scenes.show('path');
  $('boot').hidden = true;
}

/* ---------- wiring ---------- */
function begin() {
  if (!state.guide) return;
  resumeJourney();
}

$('beginBtn').addEventListener('click', begin);
$('roster').addEventListener('click', (e) => {
  const btn = e.target.closest('.char');
  if (btn) choose(btn.dataset.id);
});
$('changeGuide').addEventListener('click', () => go('viewShore', 'shore'));
$('learningPath').addEventListener('click', showHalls);
function openMode(id) {
  const mode = MODES.find((item) => item.id === id);
  if (!mode) return;
  // Tinget teaches before it tests. The values questions barely repeat between
  // papers (46 unique out of 50 asked), so drilling the old ones trains for a
  // question that will not be asked. The principles behind them do repeat.
  if (mode.teaches === 'time') return showTime();
  if (mode.teaches) return showTing();
  if (mode.duel) return showArena();
  start(mode.id);
}

$('modes').addEventListener('click', (e) => {
  const btn = e.target.closest('.mode');
  if (!btn) return;
  if (btn.dataset.id === 'sagaer') return showSagaer();
  if (btn.dataset.id === 'training') return showTraining();
  if (btn.dataset.id === 'heim') return showHeim();
  openMode(btn.dataset.id);
});
$('heimReset').addEventListener('click', () => heim?.reset());
$('trainingModes').addEventListener('click', (e) => {
  const btn = e.target.closest('.mode');
  if (btn) openMode(btn.dataset.id);
});
/* Opening a settlement folds whichever was open, and when that one sat higher up
   the page everything below it slides up — including the panel just opened. Left
   alone that is an 828px jump on a 806px screen, so the thing you asked to read
   leaves the top of the window as it opens. The browser owns the folding, so the
   correction has to live here. Only when it has actually gone above the top: a
   panel still in view is better left where it is than scrolled at.

   `toggle` does not bubble, hence the capture. The clearance under the sticky
   HUD is CSS's `scroll-margin-top`, not arithmetic. */
$('places').addEventListener('toggle', (e) => {
  const panel = e.target;
  if (!panel.open || !panel.closest?.('.place')) return;
  if (panel.getBoundingClientRect().top < 0) {
    panel.closest('.place').scrollIntoView({
      block: 'start',
      behavior: scenes.still.matches ? 'auto' : 'smooth',
    });
  }
}, true);

$('sagaHalls').addEventListener('click', (e) => {
  const read = e.target.closest('[data-read]');
  if (read) {
    sagaDoor = showSagaer;
    return showSagas(HALLS[Number(read.dataset.read)]);
  }
});

$('toMap').addEventListener('click', showMap);
$('toHalls').addEventListener('click', showHalls);
$('halls').addEventListener('click', (e) => {
  const read = e.target.closest('[data-read]');
  if (read) {
    sagaDoor = showHalls;
    return showSagas(HALLS[Number(read.dataset.read)]);
  }
  const btn = e.target.closest('.body:not([disabled])');
  if (!btn) return;
  const i = Number(btn.dataset.i);
  start(null, hallMode(HALLS[i], i));
});
$('principles').addEventListener('click', (e) => {
  const practice = e.target.closest('[data-practice]');
  if (practice) {
    const p = state.principles.find((x) => x.id === practice.dataset.practice);
    return start(null, principleMode(p));
  }
  const card = e.target.closest('.principle');
  if (card) togglePrinciple(card);
});
$('tingTest').addEventListener('click', () => start('ting'));
$('bjornDuel').addEventListener('click', () => {
  const mode = MODES.find((item) => item.id === 'dyst');
  const seed = Date.now() >>> 0;
  start(mode.id, mode, houseGhost(mode.id, seed));
});
$('friendDuel').addEventListener('click', () => start('dyst'));
$('eras').addEventListener('click', (e) => {
  const btn = e.target.closest('.body:not([disabled])');
  if (btn) start(null, eraMode(state.eras[Number(btn.dataset.i)]));
});
$('quizNext').addEventListener('click', next);
const exitRun = () => {
  const mode = state.run?.mode;
  state.run = null;
  if (mode) return leave(mode);
  if (!$('viewSagas').hidden) return sagaDoor();
  if (!$('viewSagaer').hidden) { renderPath(); return go('viewPath', 'path'); }
  if (!$('viewTime').hidden || !$('viewTing').hidden) return showTraining();
  renderPath();
  go('viewPath', 'path');
};
$('quizExit').addEventListener('click', exitRun);
$('hudBack').addEventListener('click', exitRun);
$('soundToggle').addEventListener('click', (e) => {
  state.sound = !state.sound;
  e.target.textContent = state.sound ? 'Lyd til' : 'Lyd fra';
  e.target.setAttribute('aria-pressed', String(state.sound));
  save();
  tone(600, 0.1);
});
$('resetBtn').addEventListener('click', () => {
  const who = state.profile?.name ?? '';
  if (!confirm(`Nulstil al fremgang for ${who}?`)) return;
  store().removeItem(state.profile.key);
  location.reload();
});
$('switchBtn').addEventListener('click', () => { state.run = null; showWho(); });

$('profiles').addEventListener('click', (e) => {
  const drop = e.target.closest('[data-drop]');
  if (drop) {
    e.stopPropagation();
    const name = drop.dataset.drop;
    if (!confirm(`Fjern ${name} og al fremgang på denne enhed?`)) return;
    remember(people().filter((n) => n !== name));
    localStorage.removeItem(keyFor(slugify(name)));
    if (localStorage.getItem(ACTIVE_PROFILE) === slugify(name)) localStorage.removeItem(ACTIVE_PROFILE);
    renderPeople();
    ($('profiles').querySelector('.profile') ?? $('profileName')).focus();
    return;
  }
  const card = e.target.closest('.profile');
  if (card) useProfile(card.dataset.name);
});

$('newProfile').addEventListener('submit', (e) => {
  e.preventDefault();
  const input = $('profileName');
  const name = input.value.trim();
  if (!name) return;
  if (!slugify(name)) {
    input.setCustomValidity('Brug mindst ét bogstav eller tal.');
    input.reportValidity();
    return;
  }
  input.setCustomValidity('');
  const list = people();
  // Same name twice would share one record, which is the bug we are fixing.
  const existing = list.find((item) => slugify(item) === slugify(name));
  if (!existing) remember([...list, name]);
  input.value = '';
  useProfile(existing ?? name);
});

$('guestBtn').addEventListener('click', () => {
  sessionStorage.removeItem('felag.guest');
  useProfile(null, { guest: true });
});

function enterApp() {
  const welcome = $('welcome');
  welcome.classList.add('leaving');
  setTimeout(() => {
    welcome.hidden = true;
    resumeJourney();
  }, scenes.still.matches ? 0 : 450);
}
$('welcomeStart').addEventListener('click', enterApp);
$('welcomeNavStart').addEventListener('click', enterApp);
$('welcome').addEventListener('click', (e) => {
  const hall = e.target.closest('[data-welcome-hall]');
  if (!hall || hall.disabled) return;
  welcomeHall = Number(hall.dataset.welcomeHall);
  enterApp();
});

main().catch((err) => {
  $('boot').innerHTML = `<p>Kunne ikke hente spørgsmålene.<br><small>${err}</small></p>`;
});
